export const THEMES = [
  {
    id: 'dark', name: 'Dark (VS Code)', type: 'dark',
    colors: { bg: '#1e1e1e', bg2: '#252526', bg3: '#2d2d2d', border: '#3c3c3c', accent: '#0078d4', text: '#cccccc', text2: '#858585' },
    syntax: [
      { tag: 'keyword', color: '#569cd6' },
      { tag: ['name', 'deleted', 'character', 'macroName'], color: '#569cd6' },
      { tag: ['propertyName'], color: '#9cdcfe' },
      { tag: ['processingInstruction', 'string', 'inserted', 'special(string)'], color: '#ce9178' },
      { tag: ['function(variableName)', 'labelName'], color: '#dcdcaa' },
      { tag: ['color', 'constant(name)', 'standard(name)'], color: '#4fc1ff' },
      { tag: ['definition(name)', 'separator'], color: '#d4d4d4' },
      { tag: ['typeName'], color: '#4ec9b0' },
      { tag: ['className'], color: '#4ec9b0' },
      { tag: ['number', 'changed', 'annotation', 'modifier', 'self', 'namespace'], color: '#b5cea8' },
      { tag: ['operator', 'operatorKeyword', 'url', 'escape', 'regexp', 'link', 'special(string)'], color: '#d4d4d4' },
      { tag: ['meta', 'comment'], color: '#6a9955', fontStyle: 'italic' },
      { tag: ['strong'], fontWeight: 'bold' },
      { tag: ['emphasis'], fontStyle: 'italic' },
      { tag: ['heading'], fontWeight: 'bold', color: '#569cd6' },
      { tag: ['atom', 'bool', 'special(variableName)'], color: '#569cd6' },
      { tag: ['invalid'], color: '#f44747' },
    ]
  },
  {
    id: 'one-dark', name: 'One Dark', type: 'dark',
    colors: { bg: '#282c34', bg2: '#21252b', bg3: '#333842', border: '#3e4451', accent: '#61afef', text: '#abb2bf', text2: '#5c6370' },
    syntax: [
      { tag: 'keyword', color: '#c678dd' },
      { tag: ['name', 'deleted', 'character', 'macroName'], color: '#e06c75' },
      { tag: ['propertyName'], color: '#e06c75' },
      { tag: ['processingInstruction', 'string', 'inserted', 'special(string)'], color: '#98c379' },
      { tag: ['function(variableName)', 'labelName'], color: '#61afef' },
      { tag: ['color', 'constant(name)', 'standard(name)'], color: '#d19a66' },
      { tag: ['definition(name)', 'separator'], color: '#abb2bf' },
      { tag: ['typeName'], color: '#e5c07b' },
      { tag: ['className'], color: '#e5c07b' },
      { tag: ['number', 'changed', 'annotation', 'modifier', 'self', 'namespace'], color: '#d19a66' },
      { tag: ['operator', 'operatorKeyword', 'url', 'escape', 'regexp', 'link', 'special(string)'], color: '#56b6c2' },
      { tag: ['meta', 'comment'], color: '#5c6370', fontStyle: 'italic' },
      { tag: ['strong'], fontWeight: 'bold' },
      { tag: ['emphasis'], fontStyle: 'italic' },
      { tag: ['heading'], fontWeight: 'bold', color: '#c678dd' },
      { tag: ['atom', 'bool', 'special(variableName)'], color: '#d19a66' },
      { tag: ['invalid'], color: '#f44747' },
    ]
  },
  {
    id: 'dracula', name: 'Dracula', type: 'dark',
    colors: { bg: '#282a36', bg2: '#21222c', bg3: '#343746', border: '#44475a', accent: '#bd93f9', text: '#f8f8f2', text2: '#6272a4' },
    syntax: [
      { tag: 'keyword', color: '#ff79c6' },
      { tag: ['name', 'deleted', 'character', 'macroName'], color: '#ff5555' },
      { tag: ['propertyName'], color: '#50fa7b' },
      { tag: ['processingInstruction', 'string', 'inserted', 'special(string)'], color: '#f1fa8c' },
      { tag: ['function(variableName)', 'labelName'], color: '#50fa7b' },
      { tag: ['color', 'constant(name)', 'standard(name)'], color: '#bd93f9' },
      { tag: ['definition(name)', 'separator'], color: '#f8f8f2' },
      { tag: ['typeName'], color: '#8be9fd' },
      { tag: ['className'], color: '#8be9fd' },
      { tag: ['number', 'changed', 'annotation', 'modifier', 'self', 'namespace'], color: '#bd93f9' },
      { tag: ['operator', 'operatorKeyword', 'url', 'escape', 'regexp', 'link', 'special(string)'], color: '#ff79c6' },
      { tag: ['meta', 'comment'], color: '#6272a4', fontStyle: 'italic' },
      { tag: ['strong'], fontWeight: 'bold' },
      { tag: ['emphasis'], fontStyle: 'italic' },
      { tag: ['heading'], fontWeight: 'bold', color: '#ff79c6' },
      { tag: ['atom', 'bool', 'special(variableName)'], color: '#bd93f9' },
      { tag: ['invalid'], color: '#ff5555' },
    ]
  },
  {
    id: 'monokai', name: 'Monokai', type: 'dark',
    colors: { bg: '#272822', bg2: '#1e1f1c', bg3: '#3e3d32', border: '#49483e', accent: '#a6e22e', text: '#f8f8f2', text2: '#75715e' },
    syntax: [
      { tag: 'keyword', color: '#f92672' },
      { tag: ['name', 'deleted', 'character', 'macroName'], color: '#f92672' },
      { tag: ['propertyName'], color: '#a6e22e' },
      { tag: ['processingInstruction', 'string', 'inserted', 'special(string)'], color: '#e6db74' },
      { tag: ['function(variableName)', 'labelName'], color: '#a6e22e' },
      { tag: ['color', 'constant(name)', 'standard(name)'], color: '#ae81ff' },
      { tag: ['definition(name)', 'separator'], color: '#f8f8f2' },
      { tag: ['typeName'], color: '#66d9ef' },
      { tag: ['className'], color: '#66d9ef' },
      { tag: ['number', 'changed', 'annotation', 'modifier', 'self', 'namespace'], color: '#ae81ff' },
      { tag: ['operator', 'operatorKeyword', 'url', 'escape', 'regexp', 'link', 'special(string)'], color: '#f92672' },
      { tag: ['meta', 'comment'], color: '#75715e' },
      { tag: ['strong'], fontWeight: 'bold' },
      { tag: ['emphasis'], fontStyle: 'italic' },
      { tag: ['heading'], fontWeight: 'bold', color: '#f92672' },
      { tag: ['atom', 'bool', 'special(variableName)'], color: '#ae81ff' },
      { tag: ['invalid'], color: '#f92672' },
    ]
  },
  {
    id: 'github-dark', name: 'GitHub Dark', type: 'dark',
    colors: { bg: '#0d1117', bg2: '#161b22', bg3: '#21262d', border: '#30363d', accent: '#58a6ff', text: '#c9d1d9', text2: '#8b949e' },
    syntax: [
      { tag: 'keyword', color: '#d73a49' },
      { tag: ['name', 'deleted', 'character', 'macroName'], color: '#d73a49' },
      { tag: ['propertyName'], color: '#005cc5' },
      { tag: ['processingInstruction', 'string', 'inserted', 'special(string)'], color: '#032f62' },
      { tag: ['function(variableName)', 'labelName'], color: '#6f42c1' },
      { tag: ['color', 'constant(name)', 'standard(name)'], color: '#005cc5' },
      { tag: ['definition(name)', 'separator'], color: '#24292e' },
      { tag: ['typeName'], color: '#6f42c1' },
      { tag: ['className'], color: '#6f42c1' },
      { tag: ['number', 'changed', 'annotation', 'modifier', 'self', 'namespace'], color: '#005cc5' },
      { tag: ['operator', 'operatorKeyword', 'url', 'escape', 'regexp', 'link', 'special(string)'], color: '#d73a49' },
      { tag: ['meta', 'comment'], color: '#6a737d', fontStyle: 'italic' },
      { tag: ['strong'], fontWeight: 'bold' },
      { tag: ['emphasis'], fontStyle: 'italic' },
      { tag: ['heading'], fontWeight: 'bold', color: '#d73a49' },
      { tag: ['atom', 'bool', 'special(variableName)'], color: '#005cc5' },
      { tag: ['invalid'], color: '#d73a49' },
    ]
  },
  {
    id: 'nord', name: 'Nord', type: 'dark',
    colors: { bg: '#2e3440', bg2: '#3b4252', bg3: '#434c5e', border: '#4c566a', accent: '#88c0d0', text: '#eceff4', text2: '#d8dee9' },
    syntax: [
      { tag: 'keyword', color: '#81a1c1' },
      { tag: ['name', 'deleted', 'character', 'macroName'], color: '#bf616a' },
      { tag: ['propertyName'], color: '#d8dee9' },
      { tag: ['processingInstruction', 'string', 'inserted', 'special(string)'], color: '#a3be8c' },
      { tag: ['function(variableName)', 'labelName'], color: '#88c0d0' },
      { tag: ['color', 'constant(name)', 'standard(name)'], color: '#b48ead' },
      { tag: ['definition(name)', 'separator'], color: '#d8dee9' },
      { tag: ['typeName'], color: '#ebcb8b' },
      { tag: ['className'], color: '#ebcb8b' },
      { tag: ['number', 'changed', 'annotation', 'modifier', 'self', 'namespace'], color: '#b48ead' },
      { tag: ['operator', 'operatorKeyword', 'url', 'escape', 'regexp', 'link', 'special(string)'], color: '#81a1c1' },
      { tag: ['meta', 'comment'], color: '#616e88', fontStyle: 'italic' },
      { tag: ['strong'], fontWeight: 'bold' },
      { tag: ['emphasis'], fontStyle: 'italic' },
      { tag: ['heading'], fontWeight: 'bold', color: '#81a1c1' },
      { tag: ['atom', 'bool', 'special(variableName)'], color: '#b48ead' },
      { tag: ['invalid'], color: '#bf616a' },
    ]
  },
  {
    id: 'catppuccin', name: 'Catppuccin Mocha', type: 'dark',
    colors: { bg: '#1e1e2e', bg2: '#181825', bg3: '#313244', border: '#45475a', accent: '#89b4fa', text: '#cdd6f4', text2: '#a6adc8' },
    syntax: [
      { tag: 'keyword', color: '#cba6f7' },
      { tag: ['name', 'deleted', 'character', 'macroName'], color: '#f38ba8' },
      { tag: ['propertyName'], color: '#a6e3a1' },
      { tag: ['processingInstruction', 'string', 'inserted', 'special(string)'], color: '#a6e3a1' },
      { tag: ['function(variableName)', 'labelName'], color: '#89b4fa' },
      { tag: ['color', 'constant(name)', 'standard(name)'], color: '#fab387' },
      { tag: ['definition(name)', 'separator'], color: '#cdd6f4' },
      { tag: ['typeName'], color: '#f9e2af' },
      { tag: ['className'], color: '#f9e2af' },
      { tag: ['number', 'changed', 'annotation', 'modifier', 'self', 'namespace'], color: '#fab387' },
      { tag: ['operator', 'operatorKeyword', 'url', 'escape', 'regexp', 'link', 'special(string)'], color: '#89dceb' },
      { tag: ['meta', 'comment'], color: '#6c7086', fontStyle: 'italic' },
      { tag: ['strong'], fontWeight: 'bold' },
      { tag: ['emphasis'], fontStyle: 'italic' },
      { tag: ['heading'], fontWeight: 'bold', color: '#cba6f7' },
      { tag: ['atom', 'bool', 'special(variableName)'], color: '#fab387' },
      { tag: ['invalid'], color: '#f38ba8' },
    ]
  },
  {
    id: 'tokyo-night', name: 'Tokyo Night Storm', type: 'dark',
    colors: { bg: '#1a1b26', bg2: '#16161e', bg3: '#24283b', border: '#565f89', accent: '#7aa2f7', text: '#c0caf5', text2: '#9aa5ce' },
    syntax: [
      { tag: 'keyword', color: '#bb9af7' },
      { tag: ['name', 'deleted', 'character', 'macroName'], color: '#f7768e' },
      { tag: ['propertyName'], color: '#9ece6a' },
      { tag: ['processingInstruction', 'string', 'inserted', 'special(string)'], color: '#9ece6a' },
      { tag: ['function(variableName)', 'labelName'], color: '#7aa2f7' },
      { tag: ['color', 'constant(name)', 'standard(name)'], color: '#e0af68' },
      { tag: ['definition(name)', 'separator'], color: '#c0caf5' },
      { tag: ['typeName'], color: '#e0af68' },
      { tag: ['className'], color: '#e0af68' },
      { tag: ['number', 'changed', 'annotation', 'modifier', 'self', 'namespace'], color: '#ff9e64' },
      { tag: ['operator', 'operatorKeyword', 'url', 'escape', 'regexp', 'link', 'special(string)'], color: '#89ddff' },
      { tag: ['meta', 'comment'], color: '#565f89', fontStyle: 'italic' },
      { tag: ['strong'], fontWeight: 'bold' },
      { tag: ['emphasis'], fontStyle: 'italic' },
      { tag: ['heading'], fontWeight: 'bold', color: '#bb9af7' },
      { tag: ['atom', 'bool', 'special(variableName)'], color: '#ff9e64' },
      { tag: ['invalid'], color: '#f7768e' },
    ]
  },
  {
    id: 'solarized-dark', name: 'Solarized Dark', type: 'dark',
    colors: { bg: '#002b36', bg2: '#073642', bg3: '#094454', border: '#586e75', accent: '#268bd2', text: '#839496', text2: '#657b83' },
    syntax: [
      { tag: 'keyword', color: '#859900' },
      { tag: ['name', 'deleted', 'character', 'macroName'], color: '#dc322f' },
      { tag: ['propertyName'], color: '#268bd2' },
      { tag: ['processingInstruction', 'string', 'inserted', 'special(string)'], color: '#2aa198' },
      { tag: ['function(variableName)', 'labelName'], color: '#268bd2' },
      { tag: ['color', 'constant(name)', 'standard(name)'], color: '#b58900' },
      { tag: ['definition(name)', 'separator'], color: '#93a1a1' },
      { tag: ['typeName'], color: '#b58900' },
      { tag: ['className'], color: '#b58900' },
      { tag: ['number', 'changed', 'annotation', 'modifier', 'self', 'namespace'], color: '#d33682' },
      { tag: ['operator', 'operatorKeyword', 'url', 'escape', 'regexp', 'link', 'special(string)'], color: '#6c71c4' },
      { tag: ['meta', 'comment'], color: '#586e75', fontStyle: 'italic' },
      { tag: ['strong'], fontWeight: 'bold' },
      { tag: ['emphasis'], fontStyle: 'italic' },
      { tag: ['heading'], fontWeight: 'bold', color: '#859900' },
      { tag: ['atom', 'bool', 'special(variableName)'], color: '#d33682' },
      { tag: ['invalid'], color: '#dc322f' },
    ]
  },
  {
    id: 'ayu-dark', name: 'Ayu Dark', type: 'dark',
    colors: { bg: '#0a0e14', bg2: '#131721', bg3: '#1a1f2a', border: '#2d3640', accent: '#ff8f40', text: '#b3b1ad', text2: '#707a8c' },
    syntax: [
      { tag: 'keyword', color: '#ff7733' },
      { tag: ['name', 'deleted', 'character', 'macroName'], color: '#f07178' },
      { tag: ['propertyName'], color: '#aad94c' },
      { tag: ['processingInstruction', 'string', 'inserted', 'special(string)'], color: '#c2d94c' },
      { tag: ['function(variableName)', 'labelName'], color: '#ff8f40' },
      { tag: ['color', 'constant(name)', 'standard(name)'], color: '#d2a6ff' },
      { tag: ['definition(name)', 'separator'], color: '#b3b1ad' },
      { tag: ['typeName'], color: '#59c2ff' },
      { tag: ['className'], color: '#59c2ff' },
      { tag: ['number', 'changed', 'annotation', 'modifier', 'self', 'namespace'], color: '#d2a6ff' },
      { tag: ['operator', 'operatorKeyword', 'url', 'escape', 'regexp', 'link', 'special(string)'], color: '#95e6cb' },
      { tag: ['meta', 'comment'], color: '#3e4b59', fontStyle: 'italic' },
      { tag: ['strong'], fontWeight: 'bold' },
      { tag: ['emphasis'], fontStyle: 'italic' },
      { tag: ['heading'], fontWeight: 'bold', color: '#ff7733' },
      { tag: ['atom', 'bool', 'special(variableName)'], color: '#d2a6ff' },
      { tag: ['invalid'], color: '#ff3333' },
    ]
  },
  {
    id: 'material-dark', name: 'Material Dark', type: 'dark',
    colors: { bg: '#263238', bg2: '#1e272c', bg3: '#2e3c43', border: '#37474f', accent: '#80cbc4', text: '#eeffff', text2: '#546e7a' },
    syntax: [
      { tag: 'keyword', color: '#89ddff' },
      { tag: ['name', 'deleted', 'character', 'macroName'], color: '#f07178' },
      { tag: ['propertyName'], color: '#c3e88d' },
      { tag: ['processingInstruction', 'string', 'inserted', 'special(string)'], color: '#c3e88d' },
      { tag: ['function(variableName)', 'labelName'], color: '#82aaff' },
      { tag: ['color', 'constant(name)', 'standard(name)'], color: '#ffcb6b' },
      { tag: ['definition(name)', 'separator'], color: '#eeffff' },
      { tag: ['typeName'], color: '#ffcb6b' },
      { tag: ['className'], color: '#ffcb6b' },
      { tag: ['number', 'changed', 'annotation', 'modifier', 'self', 'namespace'], color: '#f78c6c' },
      { tag: ['operator', 'operatorKeyword', 'url', 'escape', 'regexp', 'link', 'special(string)'], color: '#89ddff' },
      { tag: ['meta', 'comment'], color: '#546e7a', fontStyle: 'italic' },
      { tag: ['strong'], fontWeight: 'bold' },
      { tag: ['emphasis'], fontStyle: 'italic' },
      { tag: ['heading'], fontWeight: 'bold', color: '#89ddff' },
      { tag: ['atom', 'bool', 'special(variableName)'], color: '#f78c6c' },
      { tag: ['invalid'], color: '#ff5370' },
    ]
  },
  {
    id: 'light', name: 'Light', type: 'light',
    colors: { bg: '#ffffff', bg2: '#f3f3f3', bg3: '#e5e5e5', border: '#d0d0d0', accent: '#0078d4', text: '#333333', text2: '#666666' },
    syntax: [
      { tag: 'keyword', color: '#0000ff' },
      { tag: ['name', 'deleted', 'character', 'macroName'], color: '#a31515' },
      { tag: ['propertyName'], color: '#795e26' },
      { tag: ['processingInstruction', 'string', 'inserted', 'special(string)'], color: '#a31515' },
      { tag: ['function(variableName)', 'labelName'], color: '#795e26' },
      { tag: ['color', 'constant(name)', 'standard(name)'], color: '#0000ff' },
      { tag: ['definition(name)', 'separator'], color: '#333333' },
      { tag: ['typeName'], color: '#267f99' },
      { tag: ['className'], color: '#267f99' },
      { tag: ['number', 'changed', 'annotation', 'modifier', 'self', 'namespace'], color: '#098658' },
      { tag: ['operator', 'operatorKeyword', 'url', 'escape', 'regexp', 'link', 'special(string)'], color: '#000000' },
      { tag: ['meta', 'comment'], color: '#008000', fontStyle: 'italic' },
      { tag: ['strong'], fontWeight: 'bold' },
      { tag: ['emphasis'], fontStyle: 'italic' },
      { tag: ['heading'], fontWeight: 'bold', color: '#800000' },
      { tag: ['atom', 'bool', 'special(variableName)'], color: '#098658' },
      { tag: ['invalid'], color: '#ff0000' },
    ]
  },
  {
    id: 'hc', name: 'High Contrast', type: 'dark',
    colors: { bg: '#000000', bg2: '#0a0a0a', bg3: '#1a1a1a', border: '#6fc3df', accent: '#4fc3f7', text: '#ffffff', text2: '#c0c0c0' },
    syntax: [
      { tag: 'keyword', color: '#569cd6' },
      { tag: ['name', 'deleted', 'character', 'macroName'], color: '#4fc1ff' },
      { tag: ['propertyName'], color: '#9cdcfe' },
      { tag: ['processingInstruction', 'string', 'inserted', 'special(string)'], color: '#ce9178' },
      { tag: ['function(variableName)', 'labelName'], color: '#dcdcaa' },
      { tag: ['color', 'constant(name)', 'standard(name)'], color: '#4fc1ff' },
      { tag: ['definition(name)', 'separator'], color: '#ffffff' },
      { tag: ['typeName'], color: '#4ec9b0' },
      { tag: ['className'], color: '#4ec9b0' },
      { tag: ['number', 'changed', 'annotation', 'modifier', 'self', 'namespace'], color: '#b5cea8' },
      { tag: ['operator', 'operatorKeyword', 'url', 'escape', 'regexp', 'link', 'special(string)'], color: '#d4d4d4' },
      { tag: ['meta', 'comment'], color: '#6a9955', fontStyle: 'italic' },
      { tag: ['strong'], fontWeight: 'bold' },
      { tag: ['emphasis'], fontStyle: 'italic' },
      { tag: ['heading'], fontWeight: 'bold', color: '#569cd6' },
      { tag: ['atom', 'bool', 'special(variableName)'], color: '#b5cea8' },
      { tag: ['invalid'], color: '#f44747' },
    ]
  },
]


