// Theme definitions with syntax highlighting tuned to match mainstream IDEs.
// Each syntax entry maps CodeMirror/Lezer tag names to colors.
// Tag names are resolved via TAG_LOOKUP in CodeEditor.svelte.

export const THEMES = [
  // =====================================================================
  // VS Code Dark+ — the default. Matches VS Code's built-in dark theme.
  // =====================================================================
  {
    id: 'dark', name: 'Dark (VS Code)', type: 'dark',
    colors: { bg: '#1e1e1e', bg2: '#252526', bg3: '#2d2d2d', border: '#3c3c3c', accent: '#0078d4', text: '#cccccc', text2: '#858585' },
    syntax: [
      { tag: 'comment',             color: '#6a9955', fontStyle: 'italic' },
      { tag: 'keyword',             color: '#569cd6' },
      { tag: 'operatorKeyword',     color: '#569cd6' },
      { tag: 'string',              color: '#ce9178' },
      { tag: 'special(string)',     color: '#ce9178' },
      { tag: 'number',              color: '#b5cea8' },
      { tag: 'bool',                color: '#569cd6' },
      { tag: 'atom',                color: '#569cd6' },
      { tag: 'regexp',              color: '#d16969' },
      { tag: 'escape',              color: '#d7ba7d' },
      { tag: ['function(variableName)', 'functionName'], color: '#dcdcaa' },
      { tag: ['typeName', 'className', 'namespace'], color: '#4ec9b0' },
      { tag: 'variableName',        color: '#9cdcfe' },
      { tag: 'propertyName',        color: '#9cdcfe' },
      { tag: 'special(variableName)', color: '#9cdcfe' },
      { tag: ['definition(name)', 'labelName'], color: '#569cd6' },
      { tag: ['constant(name)', 'standard(name)'], color: '#4fc1ff' },
      { tag: ['operator', 'separator'], color: '#d4d4d4' },
      { tag: ['annotation', 'modifier', 'self'], color: '#569cd6' },
      { tag: ['macroName', 'character'], color: '#d7ba7d' },
      { tag: 'color',               color: '#569cd6' },
      { tag: 'url',                 color: '#4fc1ff' },
      { tag: 'link',                color: '#4fc1ff' },
      { tag: ['heading', 'strong'], fontWeight: 'bold', color: '#569cd6' },
      { tag: 'emphasis',            fontStyle: 'italic' },
      { tag: 'invalid',             color: '#f44747' },
      { tag: 'inserted',            color: '#b5cea8' },
      { tag: 'deleted',             color: '#ce9178' },
      { tag: 'changed',             color: '#4fc1ff' },
      { tag: ['processingInstruction', 'meta'], color: '#808080' },
    ]
  },
  // =====================================================================
  // One Dark Pro — Atom's iconic theme.
  // =====================================================================
  {
    id: 'one-dark', name: 'One Dark', type: 'dark',
    colors: { bg: '#282c34', bg2: '#21252b', bg3: '#333842', border: '#3e4451', accent: '#61afef', text: '#abb2bf', text2: '#5c6370' },
    syntax: [
      { tag: 'comment',             color: '#5c6370', fontStyle: 'italic' },
      { tag: 'keyword',             color: '#c678dd' },
      { tag: 'operatorKeyword',     color: '#c678dd' },
      { tag: 'string',              color: '#98c379' },
      { tag: 'special(string)',     color: '#98c379' },
      { tag: 'number',              color: '#d19a66' },
      { tag: 'bool',                color: '#d19a66' },
      { tag: 'atom',                color: '#d19a66' },
      { tag: 'regexp',              color: '#d19a66' },
      { tag: 'escape',              color: '#56b6c2' },
      { tag: ['function(variableName)', 'functionName'], color: '#61afef' },
      { tag: ['typeName', 'className', 'namespace'], color: '#e5c07b' },
      { tag: 'variableName',        color: '#e06c75' },
      { tag: 'propertyName',        color: '#e06c75' },
      { tag: 'special(variableName)', color: '#e06c75' },
      { tag: ['definition(name)', 'labelName'], color: '#e5c07b' },
      { tag: ['constant(name)', 'standard(name)'], color: '#d19a66' },
      { tag: ['operator', 'separator'], color: '#abb2bf' },
      { tag: ['annotation', 'modifier', 'self'], color: '#c678dd' },
      { tag: ['macroName', 'character'], color: '#e5c07b' },
      { tag: 'color',               color: '#d19a66' },
      { tag: 'url',                 color: '#61afef' },
      { tag: 'link',                color: '#61afef' },
      { tag: ['heading', 'strong'], fontWeight: 'bold', color: '#c678dd' },
      { tag: 'emphasis',            fontStyle: 'italic' },
      { tag: 'invalid',             color: '#e06c75' },
      { tag: 'inserted',            color: '#98c379' },
      { tag: 'deleted',             color: '#e06c75' },
      { tag: 'changed',             color: '#d19a66' },
      { tag: ['processingInstruction', 'meta'], color: '#5c6370' },
    ]
  },
  // =====================================================================
  // Dracula — the iconic purple/pink dark theme.
  // =====================================================================
  {
    id: 'dracula', name: 'Dracula', type: 'dark',
    colors: { bg: '#282a36', bg2: '#21222c', bg3: '#343746', border: '#44475a', accent: '#bd93f9', text: '#f8f8f2', text2: '#6272a4' },
    syntax: [
      { tag: 'comment',             color: '#6272a4', fontStyle: 'italic' },
      { tag: 'keyword',             color: '#ff79c6' },
      { tag: 'operatorKeyword',     color: '#ff79c6' },
      { tag: 'string',              color: '#f1fa8c' },
      { tag: 'special(string)',     color: '#f1fa8c' },
      { tag: 'number',              color: '#bd93f9' },
      { tag: 'bool',                color: '#bd93f9' },
      { tag: 'atom',                color: '#bd93f9' },
      { tag: 'regexp',              color: '#ff5555' },
      { tag: 'escape',              color: '#ff79c6' },
      { tag: ['function(variableName)', 'functionName'], color: '#50fa7b' },
      { tag: ['typeName', 'className', 'namespace'], color: '#8be9fd' },
      { tag: 'variableName',        color: '#ffb86c' },
      { tag: 'propertyName',        color: '#50fa7b' },
      { tag: 'special(variableName)', color: '#ffb86c' },
      { tag: ['definition(name)', 'labelName'], color: '#50fa7b' },
      { tag: ['constant(name)', 'standard(name)'], color: '#bd93f9' },
      { tag: ['operator', 'separator'], color: '#ff79c6' },
      { tag: ['annotation', 'modifier', 'self'], color: '#ff79c6' },
      { tag: ['macroName', 'character'], color: '#ffb86c' },
      { tag: 'color',               color: '#bd93f9' },
      { tag: 'url',                 color: '#8be9fd' },
      { tag: 'link',                color: '#8be9fd' },
      { tag: ['heading', 'strong'], fontWeight: 'bold', color: '#bd93f9' },
      { tag: 'emphasis',            fontStyle: 'italic' },
      { tag: 'invalid',             color: '#ff5555' },
      { tag: 'inserted',            color: '#50fa7b' },
      { tag: 'deleted',             color: '#ff5555' },
      { tag: 'changed',             color: '#f1fa8c' },
      { tag: ['processingInstruction', 'meta'], color: '#6272a4' },
    ]
  },
  // =====================================================================
  // Monokai — classic Sublime Text theme.
  // =====================================================================
  {
    id: 'monokai', name: 'Monokai', type: 'dark',
    colors: { bg: '#272822', bg2: '#1e1f1c', bg3: '#3e3d32', border: '#49483e', accent: '#a6e22e', text: '#f8f8f2', text2: '#75715e' },
    syntax: [
      { tag: 'comment',             color: '#75715e' },
      { tag: 'keyword',             color: '#f92672' },
      { tag: 'operatorKeyword',     color: '#f92672' },
      { tag: 'string',              color: '#e6db74' },
      { tag: 'special(string)',     color: '#e6db74' },
      { tag: 'number',              color: '#ae81ff' },
      { tag: 'bool',                color: '#ae81ff' },
      { tag: 'atom',                color: '#ae81ff' },
      { tag: 'regexp',              color: '#e6db74' },
      { tag: 'escape',              color: '#ae81ff' },
      { tag: ['function(variableName)', 'functionName'], color: '#a6e22e' },
      { tag: ['typeName', 'className', 'namespace'], color: '#66d9ef' },
      { tag: 'variableName',        color: '#f8f8f2' },
      { tag: 'propertyName',        color: '#a6e22e' },
      { tag: 'special(variableName)', color: '#fd971f' },
      { tag: ['definition(name)', 'labelName'], color: '#a6e22e' },
      { tag: ['constant(name)', 'standard(name)'], color: '#ae81ff' },
      { tag: ['operator', 'separator'], color: '#f92672' },
      { tag: ['annotation', 'modifier', 'self'], color: '#f92672' },
      { tag: ['macroName', 'character'], color: '#ae81ff' },
      { tag: 'color',               color: '#ae81ff' },
      { tag: 'url',                 color: '#66d9ef' },
      { tag: 'link',                color: '#66d9ef' },
      { tag: ['heading', 'strong'], fontWeight: 'bold', color: '#f92672' },
      { tag: 'emphasis',            fontStyle: 'italic' },
      { tag: 'invalid',             color: '#f92672' },
      { tag: 'inserted',            color: '#a6e22e' },
      { tag: 'deleted',             color: '#f92672' },
      { tag: 'changed',             color: '#e6db74' },
      { tag: ['processingInstruction', 'meta'], color: '#75715e' },
    ]
  },
  // =====================================================================
  // GitHub Dark — GitHub's code view dark theme.
  // =====================================================================
  {
    id: 'github-dark', name: 'GitHub Dark', type: 'dark',
    colors: { bg: '#0d1117', bg2: '#161b22', bg3: '#21262d', border: '#30363d', accent: '#58a6ff', text: '#c9d1d9', text2: '#8b949e' },
    syntax: [
      { tag: 'comment',             color: '#8b949e', fontStyle: 'italic' },
      { tag: 'keyword',             color: '#ff7b72' },
      { tag: 'operatorKeyword',     color: '#ff7b72' },
      { tag: 'string',              color: '#a5d6ff' },
      { tag: 'special(string)',     color: '#a5d6ff' },
      { tag: 'number',              color: '#79c0ff' },
      { tag: 'bool',                color: '#79c0ff' },
      { tag: 'atom',                color: '#79c0ff' },
      { tag: 'regexp',              color: '#a5d6ff' },
      { tag: 'escape',              color: '#79c0ff' },
      { tag: ['function(variableName)', 'functionName'], color: '#d2a8ff' },
      { tag: ['typeName', 'className', 'namespace'], color: '#ffa657' },
      { tag: 'variableName',        color: '#ffa657' },
      { tag: 'propertyName',        color: '#79c0ff' },
      { tag: 'special(variableName)', color: '#ffa657' },
      { tag: ['definition(name)', 'labelName'], color: '#d2a8ff' },
      { tag: ['constant(name)', 'standard(name)'], color: '#79c0ff' },
      { tag: ['operator', 'separator'], color: '#ff7b72' },
      { tag: ['annotation', 'modifier', 'self'], color: '#ff7b72' },
      { tag: ['macroName', 'character'], color: '#d2a8ff' },
      { tag: 'color',               color: '#79c0ff' },
      { tag: 'url',                 color: '#58a6ff' },
      { tag: 'link',                color: '#58a6ff' },
      { tag: ['heading', 'strong'], fontWeight: 'bold', color: '#c9d1d9' },
      { tag: 'emphasis',            fontStyle: 'italic' },
      { tag: 'invalid',             color: '#f85149' },
      { tag: 'inserted',            color: '#56d364' },
      { tag: 'deleted',             color: '#f85149' },
      { tag: 'changed',             color: '#e3b341' },
      { tag: ['processingInstruction', 'meta'], color: '#8b949e' },
    ]
  },
  // =====================================================================
  // Nord — arctic, north-bluish clean palette.
  // =====================================================================
  {
    id: 'nord', name: 'Nord', type: 'dark',
    colors: { bg: '#2e3440', bg2: '#3b4252', bg3: '#434c5e', border: '#4c566a', accent: '#88c0d0', text: '#eceff4', text2: '#d8dee9' },
    syntax: [
      { tag: 'comment',             color: '#616e88', fontStyle: 'italic' },
      { tag: 'keyword',             color: '#81a1c1' },
      { tag: 'operatorKeyword',     color: '#81a1c1' },
      { tag: 'string',              color: '#a3be8c' },
      { tag: 'special(string)',     color: '#a3be8c' },
      { tag: 'number',              color: '#b48ead' },
      { tag: 'bool',                color: '#b48ead' },
      { tag: 'atom',                color: '#b48ead' },
      { tag: 'regexp',              color: '#ebcb8b' },
      { tag: 'escape',              color: '#ebcb8b' },
      { tag: ['function(variableName)', 'functionName'], color: '#88c0d0' },
      { tag: ['typeName', 'className', 'namespace'], color: '#ebcb8b' },
      { tag: 'variableName',        color: '#d8dee9' },
      { tag: 'propertyName',        color: '#8fbcbb' },
      { tag: 'special(variableName)', color: '#d8dee9' },
      { tag: ['definition(name)', 'labelName'], color: '#8fbcbb' },
      { tag: ['constant(name)', 'standard(name)'], color: '#b48ead' },
      { tag: ['operator', 'separator'], color: '#81a1c1' },
      { tag: ['annotation', 'modifier', 'self'], color: '#81a1c1' },
      { tag: ['macroName', 'character'], color: '#b48ead' },
      { tag: 'color',               color: '#b48ead' },
      { tag: 'url',                 color: '#88c0d0' },
      { tag: 'link',                color: '#88c0d0' },
      { tag: ['heading', 'strong'], fontWeight: 'bold', color: '#88c0d0' },
      { tag: 'emphasis',            fontStyle: 'italic' },
      { tag: 'invalid',             color: '#bf616a' },
      { tag: 'inserted',            color: '#a3be8c' },
      { tag: 'deleted',             color: '#bf616a' },
      { tag: 'changed',             color: '#ebcb8b' },
      { tag: ['processingInstruction', 'meta'], color: '#616e88' },
    ]
  },
  // =====================================================================
  // Catppuccin Mocha — warm pastel dark theme.
  // =====================================================================
  {
    id: 'catppuccin', name: 'Catppuccin Mocha', type: 'dark',
    colors: { bg: '#1e1e2e', bg2: '#181825', bg3: '#313244', border: '#45475a', accent: '#89b4fa', text: '#cdd6f4', text2: '#a6adc8' },
    syntax: [
      { tag: 'comment',             color: '#6c7086', fontStyle: 'italic' },
      { tag: 'keyword',             color: '#cba6f7' },
      { tag: 'operatorKeyword',     color: '#cba6f7' },
      { tag: 'string',              color: '#a6e3a1' },
      { tag: 'special(string)',     color: '#a6e3a1' },
      { tag: 'number',              color: '#fab387' },
      { tag: 'bool',                color: '#fab387' },
      { tag: 'atom',                color: '#fab387' },
      { tag: 'regexp',              color: '#f38ba8' },
      { tag: 'escape',              color: '#fab387' },
      { tag: ['function(variableName)', 'functionName'], color: '#89b4fa' },
      { tag: ['typeName', 'className', 'namespace'], color: '#f9e2af' },
      { tag: 'variableName',        color: '#cdd6f4' },
      { tag: 'propertyName',        color: '#a6e3a1' },
      { tag: 'special(variableName)', color: '#f38ba8' },
      { tag: ['definition(name)', 'labelName'], color: '#89b4fa' },
      { tag: ['constant(name)', 'standard(name)'], color: '#fab387' },
      { tag: ['operator', 'separator'], color: '#89dceb' },
      { tag: ['annotation', 'modifier', 'self'], color: '#cba6f7' },
      { tag: ['macroName', 'character'], color: '#fab387' },
      { tag: 'color',               color: '#fab387' },
      { tag: 'url',                 color: '#89b4fa' },
      { tag: 'link',                color: '#89b4fa' },
      { tag: ['heading', 'strong'], fontWeight: 'bold', color: '#cba6f7' },
      { tag: 'emphasis',            fontStyle: 'italic' },
      { tag: 'invalid',             color: '#f38ba8' },
      { tag: 'inserted',            color: '#a6e3a1' },
      { tag: 'deleted',             color: '#f38ba8' },
      { tag: 'changed',             color: '#f9e2af' },
      { tag: ['processingInstruction', 'meta'], color: '#6c7086' },
    ]
  },
  // =====================================================================
  // Tokyo Night Storm — neon-inspired dark theme.
  // =====================================================================
  {
    id: 'tokyo-night', name: 'Tokyo Night Storm', type: 'dark',
    colors: { bg: '#1a1b26', bg2: '#16161e', bg3: '#24283b', border: '#565f89', accent: '#7aa2f7', text: '#c0caf5', text2: '#9aa5ce' },
    syntax: [
      { tag: 'comment',             color: '#565f89', fontStyle: 'italic' },
      { tag: 'keyword',             color: '#bb9af7' },
      { tag: 'operatorKeyword',     color: '#bb9af7' },
      { tag: 'string',              color: '#9ece6a' },
      { tag: 'special(string)',     color: '#9ece6a' },
      { tag: 'number',              color: '#ff9e64' },
      { tag: 'bool',                color: '#ff9e64' },
      { tag: 'atom',                color: '#ff9e64' },
      { tag: 'regexp',              color: '#ff9e64' },
      { tag: 'escape',              color: '#e0af68' },
      { tag: ['function(variableName)', 'functionName'], color: '#7aa2f7' },
      { tag: ['typeName', 'className', 'namespace'], color: '#e0af68' },
      { tag: 'variableName',        color: '#c0caf5' },
      { tag: 'propertyName',        color: '#7dcfff' },
      { tag: 'special(variableName)', color: '#ff9e64' },
      { tag: ['definition(name)', 'labelName'], color: '#7aa2f7' },
      { tag: ['constant(name)', 'standard(name)'], color: '#ff9e64' },
      { tag: ['operator', 'separator'], color: '#89ddff' },
      { tag: ['annotation', 'modifier', 'self'], color: '#bb9af7' },
      { tag: ['macroName', 'character'], color: '#ff9e64' },
      { tag: 'color',               color: '#ff9e64' },
      { tag: 'url',                 color: '#7aa2f7' },
      { tag: 'link',                color: '#7aa2f7' },
      { tag: ['heading', 'strong'], fontWeight: 'bold', color: '#bb9af7' },
      { tag: 'emphasis',            fontStyle: 'italic' },
      { tag: 'invalid',             color: '#f7768e' },
      { tag: 'inserted',            color: '#9ece6a' },
      { tag: 'deleted',             color: '#f7768e' },
      { tag: 'changed',             color: '#e0af68' },
      { tag: ['processingInstruction', 'meta'], color: '#565f89' },
    ]
  },
  // =====================================================================
  // Solarized Dark — Ethan Schoonover's precision color theme.
  // =====================================================================
  {
    id: 'solarized-dark', name: 'Solarized Dark', type: 'dark',
    colors: { bg: '#002b36', bg2: '#073642', bg3: '#094454', border: '#586e75', accent: '#268bd2', text: '#839496', text2: '#657b83' },
    syntax: [
      { tag: 'comment',             color: '#586e75', fontStyle: 'italic' },
      { tag: 'keyword',             color: '#859900' },
      { tag: 'operatorKeyword',     color: '#859900' },
      { tag: 'string',              color: '#2aa198' },
      { tag: 'special(string)',     color: '#2aa198' },
      { tag: 'number',              color: '#d33682' },
      { tag: 'bool',                color: '#d33682' },
      { tag: 'atom',                color: '#d33682' },
      { tag: 'regexp',              color: '#dc322f' },
      { tag: 'escape',              color: '#dc322f' },
      { tag: ['function(variableName)', 'functionName'], color: '#268bd2' },
      { tag: ['typeName', 'className', 'namespace'], color: '#b58900' },
      { tag: 'variableName',        color: '#839496' },
      { tag: 'propertyName',        color: '#268bd2' },
      { tag: 'special(variableName)', color: '#d33682' },
      { tag: ['definition(name)', 'labelName'], color: '#268bd2' },
      { tag: ['constant(name)', 'standard(name)'], color: '#d33682' },
      { tag: ['operator', 'separator'], color: '#6c71c4' },
      { tag: ['annotation', 'modifier', 'self'], color: '#859900' },
      { tag: ['macroName', 'character'], color: '#dc322f' },
      { tag: 'color',               color: '#d33682' },
      { tag: 'url',                 color: '#268bd2' },
      { tag: 'link',                color: '#268bd2' },
      { tag: ['heading', 'strong'], fontWeight: 'bold', color: '#93a1a1' },
      { tag: 'emphasis',            fontStyle: 'italic' },
      { tag: 'invalid',             color: '#dc322f' },
      { tag: 'inserted',            color: '#859900' },
      { tag: 'deleted',             color: '#dc322f' },
      { tag: 'changed',             color: '#b58900' },
      { tag: ['processingInstruction', 'meta'], color: '#586e75' },
    ]
  },
  // =====================================================================
  // Ayu Dark — warm, minimal dark theme.
  // =====================================================================
  {
    id: 'ayu-dark', name: 'Ayu Dark', type: 'dark',
    colors: { bg: '#0a0e14', bg2: '#131721', bg3: '#1a1f2a', border: '#2d3640', accent: '#ff8f40', text: '#b3b1ad', text2: '#707a8c' },
    syntax: [
      { tag: 'comment',             color: '#3e4b59', fontStyle: 'italic' },
      { tag: 'keyword',             color: '#ff7733' },
      { tag: 'operatorKeyword',     color: '#ff7733' },
      { tag: 'string',              color: '#c2d94c' },
      { tag: 'special(string)',     color: '#c2d94c' },
      { tag: 'number',              color: '#d2a6ff' },
      { tag: 'bool',                color: '#d2a6ff' },
      { tag: 'atom',                color: '#d2a6ff' },
      { tag: 'regexp',              color: '#95e6cb' },
      { tag: 'escape',              color: '#95e6cb' },
      { tag: ['function(variableName)', 'functionName'], color: '#ff8f40' },
      { tag: ['typeName', 'className', 'namespace'], color: '#59c2ff' },
      { tag: 'variableName',        color: '#b3b1ad' },
      { tag: 'propertyName',        color: '#aad94c' },
      { tag: 'special(variableName)', color: '#d2a6ff' },
      { tag: ['definition(name)', 'labelName'], color: '#ff8f40' },
      { tag: ['constant(name)', 'standard(name)'], color: '#d2a6ff' },
      { tag: ['operator', 'separator'], color: '#95e6cb' },
      { tag: ['annotation', 'modifier', 'self'], color: '#ff7733' },
      { tag: ['macroName', 'character'], color: '#d2a6ff' },
      { tag: 'color',               color: '#d2a6ff' },
      { tag: 'url',                 color: '#59c2ff' },
      { tag: 'link',                color: '#59c2ff' },
      { tag: ['heading', 'strong'], fontWeight: 'bold', color: '#ff7733' },
      { tag: 'emphasis',            fontStyle: 'italic' },
      { tag: 'invalid',             color: '#ff3333' },
      { tag: 'inserted',            color: '#c2d94c' },
      { tag: 'deleted',             color: '#f07178' },
      { tag: 'changed',             color: '#ff8f40' },
      { tag: ['processingInstruction', 'meta'], color: '#3e4b59' },
    ]
  },
  // =====================================================================
  // Material Dark — Google's Material Design palette.
  // =====================================================================
  {
    id: 'material-dark', name: 'Material Dark', type: 'dark',
    colors: { bg: '#263238', bg2: '#1e272c', bg3: '#2e3c43', border: '#37474f', accent: '#80cbc4', text: '#eeffff', text2: '#546e7a' },
    syntax: [
      { tag: 'comment',             color: '#546e7a', fontStyle: 'italic' },
      { tag: 'keyword',             color: '#89ddff' },
      { tag: 'operatorKeyword',     color: '#89ddff' },
      { tag: 'string',              color: '#c3e88d' },
      { tag: 'special(string)',     color: '#c3e88d' },
      { tag: 'number',              color: '#f78c6c' },
      { tag: 'bool',                color: '#f78c6c' },
      { tag: 'atom',                color: '#f78c6c' },
      { tag: 'regexp',              color: '#c3e88d' },
      { tag: 'escape',              color: '#89ddff' },
      { tag: ['function(variableName)', 'functionName'], color: '#82aaff' },
      { tag: ['typeName', 'className', 'namespace'], color: '#ffcb6b' },
      { tag: 'variableName',        color: '#eeffff' },
      { tag: 'propertyName',        color: '#c3e88d' },
      { tag: 'special(variableName)', color: '#f78c6c' },
      { tag: ['definition(name)', 'labelName'], color: '#82aaff' },
      { tag: ['constant(name)', 'standard(name)'], color: '#f78c6c' },
      { tag: ['operator', 'separator'], color: '#89ddff' },
      { tag: ['annotation', 'modifier', 'self'], color: '#89ddff' },
      { tag: ['macroName', 'character'], color: '#f78c6c' },
      { tag: 'color',               color: '#f78c6c' },
      { tag: 'url',                 color: '#82aaff' },
      { tag: 'link',                color: '#82aaff' },
      { tag: ['heading', 'strong'], fontWeight: 'bold', color: '#89ddff' },
      { tag: 'emphasis',            fontStyle: 'italic' },
      { tag: 'invalid',             color: '#ff5370' },
      { tag: 'inserted',            color: '#c3e88d' },
      { tag: 'deleted',             color: '#ff5370' },
      { tag: 'changed',             color: '#ffcb6b' },
      { tag: ['processingInstruction', 'meta'], color: '#546e7a' },
    ]
  },
  // =====================================================================
  // Light — VS Code Light+ theme.
  // =====================================================================
  {
    id: 'light', name: 'Light', type: 'light',
    colors: { bg: '#ffffff', bg2: '#f3f3f3', bg3: '#e5e5e5', border: '#d0d0d0', accent: '#0078d4', text: '#333333', text2: '#666666' },
    syntax: [
      { tag: 'comment',             color: '#008000', fontStyle: 'italic' },
      { tag: 'keyword',             color: '#0000ff' },
      { tag: 'operatorKeyword',     color: '#0000ff' },
      { tag: 'string',              color: '#a31515' },
      { tag: 'special(string)',     color: '#a31515' },
      { tag: 'number',              color: '#098658' },
      { tag: 'bool',                color: '#0000ff' },
      { tag: 'atom',                color: '#098658' },
      { tag: 'regexp',              color: '#811f3f' },
      { tag: 'escape',              color: '#ee0000' },
      { tag: ['function(variableName)', 'functionName'], color: '#795e26' },
      { tag: ['typeName', 'className', 'namespace'], color: '#267f99' },
      { tag: 'variableName',        color: '#001080' },
      { tag: 'propertyName',        color: '#0451a5' },
      { tag: 'special(variableName)', color: '#001080' },
      { tag: ['definition(name)', 'labelName'], color: '#795e26' },
      { tag: ['constant(name)', 'standard(name)'], color: '#0070c1' },
      { tag: ['operator', 'separator'], color: '#000000' },
      { tag: ['annotation', 'modifier', 'self'], color: '#0000ff' },
      { tag: ['macroName', 'character'], color: '#098658' },
      { tag: 'color',               color: '#098658' },
      { tag: 'url',                 color: '#0451a5' },
      { tag: 'link',                color: '#0451a5' },
      { tag: ['heading', 'strong'], fontWeight: 'bold', color: '#000080' },
      { tag: 'emphasis',            fontStyle: 'italic' },
      { tag: 'invalid',             color: '#ff0000' },
      { tag: 'inserted',            color: '#098658' },
      { tag: 'deleted',             color: '#a31515' },
      { tag: 'changed',             color: '#0451a5' },
      { tag: ['processingInstruction', 'meta'], color: '#808080' },
    ]
  },
  // =====================================================================
  // High Contrast — accessibility-focused.
  // =====================================================================
  {
    id: 'hc', name: 'High Contrast', type: 'dark',
    colors: { bg: '#000000', bg2: '#0a0a0a', bg3: '#1a1a1a', border: '#6fc3df', accent: '#4fc3f7', text: '#ffffff', text2: '#c0c0c0' },
    syntax: [
      { tag: 'comment',             color: '#6a9955', fontStyle: 'italic' },
      { tag: 'keyword',             color: '#569cd6' },
      { tag: 'operatorKeyword',     color: '#569cd6' },
      { tag: 'string',              color: '#ce9178' },
      { tag: 'special(string)',     color: '#ce9178' },
      { tag: 'number',              color: '#b5cea8' },
      { tag: 'bool',                color: '#569cd6' },
      { tag: 'atom',                color: '#b5cea8' },
      { tag: 'regexp',              color: '#d16969' },
      { tag: 'escape',              color: '#d7ba7d' },
      { tag: ['function(variableName)', 'functionName'], color: '#dcdcaa' },
      { tag: ['typeName', 'className', 'namespace'], color: '#4ec9b0' },
      { tag: 'variableName',        color: '#9cdcfe' },
      { tag: 'propertyName',        color: '#9cdcfe' },
      { tag: 'special(variableName)', color: '#9cdcfe' },
      { tag: ['definition(name)', 'labelName'], color: '#569cd6' },
      { tag: ['constant(name)', 'standard(name)'], color: '#4fc1ff' },
      { tag: ['operator', 'separator'], color: '#d4d4d4' },
      { tag: ['annotation', 'modifier', 'self'], color: '#569cd6' },
      { tag: ['macroName', 'character'], color: '#d7ba7d' },
      { tag: 'color',               color: '#569cd6' },
      { tag: 'url',                 color: '#4fc1ff' },
      { tag: 'link',                color: '#4fc1ff' },
      { tag: ['heading', 'strong'], fontWeight: 'bold', color: '#569cd6' },
      { tag: 'emphasis',            fontStyle: 'italic' },
      { tag: 'invalid',             color: '#f44747' },
      { tag: 'inserted',            color: '#b5cea8' },
      { tag: 'deleted',             color: '#ce9178' },
      { tag: 'changed',             color: '#4fc1ff' },
      { tag: ['processingInstruction', 'meta'], color: '#c0c0c0' },
    ]
  },
]
