package builtins

import "StarCore/internal/skill"

func AllSkills() []skill.SkillDef {
	return []skill.SkillDef{
		{ID: "generate-test", Name: "生成单元测试", Icon: "🧪", Category: "code", Trigger: "selection", ResultType: "code",
			Description: "为选中的代码自动生成单元测试，覆盖正常路径、边界情况和错误场景",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `为以下 {language} 代码生成完整的单元测试。要求：1.使用主流测试框架 2.覆盖正常路径 3.覆盖边界值和极端值 4.覆盖错误场景 5.命名清晰体现测试意图 6.table-driven 风格。补充：{input}。代码({file}): {code}`,
		},
		{ID: "code-review", Name: "代码审查", Icon: "🔍", Category: "code", Trigger: "selection", ResultType: "text",
			Description: "对选中代码进行全面审查，输出问题列表和改进建议",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `审查以下 {language} 代码。维度：1.正确性 2.可读性 3.性能 4.安全性 5.可维护性 6.错误处理。输出(每个问题)：严重程度(高/中/低)、位置、描述、修改建议(含代码)。补充：{input}。代码({file}): {code}`,
		},
		{ID: "refactor", Name: "重构建议", Icon: "♻️", Category: "code", Trigger: "selection", ResultType: "diff",
			Description: "分析代码并提供重构方案，以 diff 格式输出修改建议",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `分析以下 {language} 代码并提供重构方案。原则：1.单一职责 2.消除重复 3.简化逻辑 4.改善命名 5.合理抽象不过度 6.保持行为不变。输出：重构说明、重构后代码、修改要点。补充：{input}。代码({file}): {code}`,
		},
		{ID: "generate-doc", Name: "生成文档", Icon: "📝", Category: "code", Trigger: "selection", ResultType: "code",
			Description: "为选中代码生成规范的文档注释",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `为以下 {language} 代码生成规范文档注释。使用标准格式(JSDoc/GoDoc/Docstring等)，描述用途、参数类型和含义、返回值、异常。补充：{input}。代码({file}): {code}`,
		},
		{ID: "explain-code", Name: "解释代码", Icon: "💡", Category: "code", Trigger: "selection", ResultType: "text",
			Description: "逐段解释代码逻辑，帮助理解复杂代码",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `逐段解释以下 {language} 代码。按段落分组，先概述流程再深入细节，解释"为什么"而非"做了什么"，标注关键决策和风险点。中文解释，代码和专有名词保持英文。补充：{input}。代码({file}): {code}`,
		},
		{ID: "fix-bug", Name: "修复 Bug", Icon: "🔧", Category: "code", Trigger: "error", ResultType: "diff",
			Description: "根据错误信息分析根因并提供修复方案",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `根据错误信息定位并修复 Bug。流程：1.分析错误 2.追踪根因 3.最小化修复 4.验证覆盖 5.检查副作用。输出：根因分析、修复方案、修复后代码、验证建议。补充：{input}。错误: {error}。代码({file}): {code}`,
		},
		{ID: "commit-message", Name: "生成 Commit Message", Icon: "📋", Category: "git", Trigger: "manual", ResultType: "text",
			Description: "根据代码变更生成规范的 Conventional Commits 格式提交信息",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `根据代码变更生成 Conventional Commits 格式的 Commit Message。类型:feat/fix/docs/style/refactor/perf/test/build/ci/chore/revert。描述简短精准(50字符内)。正文说明WHY而非WHAT。补充：{input}。变更({file}): {content}`,
		},
		{ID: "sql-optimize", Name: "SQL 优化", Icon: "🚀", Category: "database", Trigger: "selection", ResultType: "text",
			Description: "分析 SQL 查询并提供索引和优化建议",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `分析以下 SQL。维度：1.索引建议(B-tree/Hash/复合/覆盖) 2.查询改写(CTE/消除子查询) 3.执行计划预估 4.N+1/隐式转换等问题 5.数据量估算。输出：问题点、优化后SQL(标注理由)、推荐索引(CREATE INDEX)、预期提升。补充：{input}。SQL: {code}`,
		},
		{ID: "debug-analyze", Name: "调试分析", Icon: "🐛", Category: "code", Trigger: "error", ResultType: "text",
			Description: "根据错误信息和上下文进行深度调试分析，定位根因",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `深度调试分析。步骤：1.解读错误信息(类型/位置/调用栈) 2.追踪数据流 3.假设验证 4.找根因 5.修复建议。输出：错误解读、数据流追踪、根因、修复代码、预防建议。补充：{input}。错误: {error}。代码({file}): {code}`,
		},
		{ID: "git-pr-review", Name: "PR 审查", Icon: "✅", Category: "git", Trigger: "manual", ResultType: "text",
			Description: "模拟 Code Review，检查代码变更的完整性、正确性和规范",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `PR 级别审查。维度：1.变更完整性 2.正确性 3.风格一致性 4.测试覆盖 5.性能影响 6.安全 7.文档。输出：总体评价、必须修改(blocker)、建议修改(suggestion)、疑问(question)、LGTM点。补充：{input}。变更({file}): {content}`,
		},
		{ID: "api-design", Name: "API 设计", Icon: "🔌", Category: "design", Trigger: "manual", ResultType: "text",
			Description: "设计 RESTful 或 RPC API 接口，输出完整的接口文档",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `设计 API 方案。包含：1.资源建模 2.RESTful端点(名词/层级) 3.JSON Schema 4.HTTP状态码 5.统一错误格式 6.分页/排序/过滤 7.版本策略 8.认证(JWT/OAuth2) 9.限流。输出：API概述、基础URL和认证、端点列表、请求响应示例、错误码。补充：{input}。参考({file}): {code}`,
		},
		{ID: "security-check", Name: "安全检查", Icon: "🛡️", Category: "code", Trigger: "selection", ResultType: "text",
			Description: "对代码进行安全漏洞扫描，输出风险列表和修复建议",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `OWASP Top 10 安全审查。检查：注入漏洞/认证失效/敏感数据泄露/XXE/SSRF/越权/XSS/CSRF/反序列化/路径穿越/依赖CVE。输出(每个)：🔴🟡🟢级别、类型、位置、风险说明、攻击场景、修复方案(含代码)。补充：{input}。代码({file}): {code}`,
		},
		{ID: "performance-profile", Name: "性能分析", Icon: "📊", Category: "code", Trigger: "selection", ResultType: "text",
			Description: "分析代码性能瓶颈，提供具体优化方案和预期收益",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `性能分析。维度：1.时间/空间复杂度 2.内存使用和泄漏 3.I/O效率 4.并发问题(锁竞争/死锁) 5.缓存策略 6.批量处理。输出：性能概览、瓶颈列表(影响力排序)、优化后代码示例、预期提升、测量建议。补充：{input}。代码({file}): {code}`,
		},
		{ID: "config-init", Name: "项目初始化配置", Icon: "⚙️", Category: "project", Trigger: "manual", ResultType: "code",
			Description: "为新项目生成最佳实践的配置文件（ESLint/Prettier/Docker/GitHub Actions 等）",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `为 {language} 项目生成最佳实践配置。按需生成：Linter/Formatter/Docker/CI/CD/依赖管理/.env.example/.gitignore/.editorconfig。使用社区最推荐方案，配置可直接使用并带注释。补充：{input}。项目({file}): {content}`,
		},
		{ID: "log-analyze", Name: "日志分析", Icon: "📋", Category: "ops", Trigger: "selection", ResultType: "text",
			Description: "分析应用日志，识别错误模式、异常趋势和优化建议",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `日志分析。维度：1.错误统计(类型/频率/时间) 2.异常模式 3.性能指标 4.关联分析 5.告警建议。输出：摘要(3-5条)、错误详情、根因推测、修复建议(按优先级)、监控建议。补充：{input}。日志({file}): {code}`,
		},
		{ID: "dependency-scan", Name: "依赖分析", Icon: "📦", Category: "project", Trigger: "manual", ResultType: "text",
			Description: "分析项目依赖，检查过期、漏洞、许可证冲突和冗余",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `分析 {language} 项目依赖。维度：1.过期依赖(标注主/次/修版本) 2.CVE漏洞(CVSS分数) 3.许可证冲突 4.冗余依赖 5.版本锁定策略 6.体积分析 7.轻量替代。输出：概况、立即处理项、建议更新、可移除项、优化建议。补充：{input}。依赖文件({file}): {code}`,
		},
		{ID: "error-handle", Name: "错误处理完善", Icon: "🔄", Category: "code", Trigger: "selection", ResultType: "diff",
			Description: "完善代码的错误处理，添加适当的异常捕获、日志和降级逻辑",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `完善 {language} 代码错误处理。方向：1.缺失的error检查 2.错误类型 3.上下文信息 4.wrap/unwrap 5.降级/fallback 6.日志 7.重试逻辑 8.panic recover。输出：问题列表、完善后代码(标注改动目的)、最佳实践建议。补充：{input}。代码({file}): {code}`,
		},
		{ID: "i18n-translate", Name: "国际化翻译", Icon: "🌍", Category: "code", Trigger: "selection", ResultType: "code",
			Description: "将代码中的硬编码字符串提取并翻译为多语言 (i18n) 格式",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `将 {language} 代码中的用户可见文本提取为国际化格式。使用主流 i18n 方案，生成中英双语语言文件，key 命名有语义(error.validation.required)。输出：提取列表(原文→key→中文→英文)、修改后代码、语言文件。补充：{input}。代码({file}): {code}`,
		},
		{ID: "data-model", Name: "数据建模", Icon: "🗄️", Category: "design", Trigger: "manual", ResultType: "text",
			Description: "根据需求设计数据库表结构、索引和关系",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `设计数据库表结构。包含：实体识别、关系建模(1:1/1:N/M:N)、字段设计(类型/默认值/可空)、索引(主键/唯一/复合)、约束(FK/CHECK)、命名规范、扩展性(预留/软删除/时间戳)、分库分表策略。输出：ER说明、CREATE TABLE语句、索引说明、迁移策略。补充：{input}。参考({file}): {code}`,
		},
		{ID: "regex-explain", Name: "正则表达式解释", Icon: "🔤", Category: "code", Trigger: "selection", ResultType: "text",
			Description: "逐段解析正则表达式，说明匹配规则和实际效果",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `逐段解析正则表达式。拆成段落说明(正则片段→中文→匹配示例)，标注量词/锚点/捕获组/环视，给出3-5个匹配和不匹配用例，如有优化给出优化版，说明性能(回溯风险)。补充：{input}。正则: {code}`,
		},
		{ID: "migration-script", Name: "数据库迁移脚本", Icon: "📜", Category: "database", Trigger: "manual", ResultType: "code",
			Description: "生成数据库 migration 脚本（up/down），支持回滚",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `生成迁移脚本。Up(正向迁移)、Down(回滚)、幂等(IF EXISTS/NOT EXISTS)、事务安全、数据迁移逻辑。输出：Up脚本、Down脚本、迁移说明(影响/耗时/风险)、验证SQL。补充：{input}。参考({file}): {content}`,
		},
		{ID: "project-readme", Name: "生成 README", Icon: "📖", Category: "project", Trigger: "manual", ResultType: "text",
			Description: "根据项目结构和代码自动生成专业的 README.md",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `生成专业的 README.md。结构：项目名+徽章、一句话简介、特性列表、快速开始(3步)、使用示例(核心用法)、配置说明、项目结构、技术栈、贡献指南、许可证。每个部分直接给可用内容，markdown格式，代码块标注语言，命令可直接复制。补充：{input}。项目({file}): {content}`,
		},
		{ID: "test-data", Name: "生成测试数据", Icon: "🎲", Category: "code", Trigger: "manual", ResultType: "code",
			Description: "为代码中的数据结构生成随机但合理的测试数据",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `为 {language} 数据结构生成测试数据。覆盖：正常值、边界值、异常值、关联一致性、null/空字符串/最大最小值/特殊字符。用 faker/random 库生成(非硬编码)，标注数据量级建议。输出：生成代码、数据样例(前5条)、faker库安装方法。补充：{input}。数据结构({file}): {code}`,
		},
		{ID: "bash-script", Name: "Shell 脚本生成", Icon: "💻", Category: "ops", Trigger: "manual", ResultType: "code",
			Description: "生成健壮的 Shell 脚本，包含错误处理、参数解析、日志",
			AssociatedAgents: []string{"universal-assistant"},
			PromptTemplate: `生成生产级 Shell 脚本。包含：set -euo pipefail、参数解析(--help/--verbose)、trap清理、日志函数(INFO/WARN/ERROR带时间戳)、幂等性、跨平台说明、颜色输出、进度提示。输出：完整脚本、使用说明(参数+示例)、依赖说明。补充：{input}。参考: {content}`,
		},
	}
}
