// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {provider} from '../models';
import {mcp} from '../models';
import {main} from '../models';
import {files} from '../models';
import {skill} from '../models';
import {agent} from '../models';
import {memory} from '../models';
import {git} from '../models';
import {lsp} from '../models';

export function AIChat(arg1:provider.ChatRequest):Promise<string>;

export function AIChatStream(arg1:provider.ChatRequest):Promise<void>;

export function AICompletion(arg1:string,arg2:provider.CompletionRequest):Promise<string>;

export function AddMCPServer(arg1:mcp.MCPServerConfig):Promise<void>;

export function AnalyzeProject(arg1:string):Promise<string>;

export function ApplyDiff(arg1:main.ApplyDiffRequest):Promise<void>;

export function CloseWindow():Promise<void>;

export function ComputeDiff(arg1:string,arg2:string):Promise<Array<files.DiffHunk>>;

export function ConnectTerminal(arg1:string):Promise<void>;

export function CreateDir(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteKnowledge(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function ExecuteCommand(arg1:string):Promise<string>;

export function ExecuteSkill(arg1:string,arg2:skill.SkillContext,arg3:string,arg4:string):Promise<void>;

export function ExecuteToolCall(arg1:agent.ToolCall):Promise<agent.ToolResult>;

export function GetAgentConfig(arg1:string):Promise<agent.AgentDef>;

export function GetAgents():Promise<Array<agent.AgentDef>>;

export function GetConversations(arg1:string):Promise<Array<memory.Conversation>>;

export function GetKnowledge(arg1:string):Promise<Array<memory.Knowledge>>;

export function GetMCPServers():Promise<Array<mcp.MCPServerConfig>>;

export function GetMessages(arg1:string):Promise<Array<memory.Message>>;

export function GetModels(arg1:string):Promise<Array<provider.Model>>;

export function GetProjectAnalysis(arg1:string):Promise<string>;

export function GetProviders():Promise<Array<provider.ProviderInfo>>;

export function GetSkills():Promise<Array<skill.SkillDef>>;

export function GetTokenUsage(arg1:string):Promise<memory.TokenUsageStats>;

export function GetTools():Promise<Array<agent.ToolDef>>;

export function GitBranch(arg1:string):Promise<string>;

export function GitCheckout(arg1:string,arg2:string):Promise<string>;

export function GitCommit(arg1:string,arg2:string):Promise<void>;

export function GitCreateBranch(arg1:string,arg2:string):Promise<string>;

export function GitDiff(arg1:string,arg2:string):Promise<string>;

export function GitFetch(arg1:string):Promise<string>;

export function GitLog(arg1:string,arg2:number):Promise<Array<git.LogEntry>>;

export function GitMerge(arg1:string,arg2:string):Promise<string>;

export function GitPull(arg1:string):Promise<string>;

export function GitPush(arg1:string):Promise<string>;

export function GitStage(arg1:string,arg2:string):Promise<void>;

export function GitStash(arg1:string,arg2:string):Promise<string>;

export function GitStatus(arg1:string):Promise<Array<git.StatusEntry>>;

export function GitStatusAndBranch(arg1:string):Promise<Record<string, any>>;

export function GitUnstage(arg1:string,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function InstallSkillFromURL(arg1:string):Promise<void>;

export function IsProviderConfigured():Promise<boolean>;

export function KillTerminal(arg1:string):Promise<void>;

export function LSPCloseFile(arg1:string):Promise<void>;

export function LSPCompletions(arg1:string,arg2:number,arg3:number):Promise<Array<lsp.FrontendCompletion>>;

export function LSPDefinition(arg1:string,arg2:number,arg3:number):Promise<Array<lsp.Location>>;

export function LSPDidChange(arg1:string,arg2:string):Promise<void>;

export function LSPDidOpen(arg1:string,arg2:string):Promise<void>;

export function LSPHover(arg1:string,arg2:number,arg3:number):Promise<lsp.Hover>;

export function LSPShutdown():Promise<void>;

export function ListDir(arg1:string):Promise<Array<files.FileInfo>>;

export function ListTerminals():Promise<Array<Record<string, any>>>;

export function LoadCustomModels():Promise<Array<main.CustomModelEntry>>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function NewTerminal(arg1:string):Promise<string>;

export function OpenFolder():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileWithLSP(arg1:string):Promise<string>;

export function RemoveMCPServer(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function ReplaceInFiles(arg1:string,arg2:string,arg3:files.SearchOptions):Promise<void>;

export function SaveConversation(arg1:memory.Conversation):Promise<void>;

export function SaveCustomModels(arg1:Array<main.CustomModelEntry>):Promise<void>;

export function SaveKnowledge(arg1:memory.Knowledge):Promise<void>;

export function SaveMessage(arg1:memory.Message):Promise<void>;

export function SaveSkill(arg1:skill.SkillDef):Promise<void>;

export function SaveTokenUsageEntry(arg1:memory.TokenUsageEntry):Promise<void>;

export function SearchFiles(arg1:string,arg2:files.SearchOptions):Promise<Array<files.SearchResult>>;

export function SetProjectPath(arg1:string):Promise<void>;

export function SetProviderConfig(arg1:string,arg2:provider.ProviderConfig):Promise<void>;

export function SetToolAutoApprove(arg1:string,arg2:boolean):Promise<void>;

export function StartMCPServer(arg1:string):Promise<void>;

export function StartTerminal(arg1:string):Promise<void>;

export function StopGenerating():Promise<void>;

export function StopMCPServer(arg1:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TerminalWrite(arg1:string,arg2:string):Promise<void>;

export function TestProvider(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteFileWithLSP(arg1:string,arg2:string):Promise<void>;
