// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIChat(arg1) {
  return window['go']['main']['App']['AIChat'](arg1);
}

export function AIChatStream(arg1) {
  return window['go']['main']['App']['AIChatStream'](arg1);
}

export function AICompletion(arg1, arg2) {
  return window['go']['main']['App']['AICompletion'](arg1, arg2);
}

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function AnalyzeProject(arg1) {
  return window['go']['main']['App']['AnalyzeProject'](arg1);
}

export function ApplyDiff(arg1) {
  return window['go']['main']['App']['ApplyDiff'](arg1);
}

export function ClearTokenUsage() {
  return window['go']['main']['App']['ClearTokenUsage']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function ComputeDiff(arg1, arg2) {
  return window['go']['main']['App']['ComputeDiff'](arg1, arg2);
}

export function ConnectTerminal(arg1) {
  return window['go']['main']['App']['ConnectTerminal'](arg1);
}

export function CreateDir(arg1) {
  return window['go']['main']['App']['CreateDir'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteKnowledge(arg1) {
  return window['go']['main']['App']['DeleteKnowledge'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function ExecuteSkill(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteSkill'](arg1, arg2, arg3, arg4);
}

export function ExecuteToolCall(arg1) {
  return window['go']['main']['App']['ExecuteToolCall'](arg1);
}

export function GetAgentConfig(arg1) {
  return window['go']['main']['App']['GetAgentConfig'](arg1);
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetConversations(arg1) {
  return window['go']['main']['App']['GetConversations'](arg1);
}

export function GetKnowledge(arg1) {
  return window['go']['main']['App']['GetKnowledge'](arg1);
}

export function GetMCPServers() {
  return window['go']['main']['App']['GetMCPServers']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetModels(arg1) {
  return window['go']['main']['App']['GetModels'](arg1);
}

export function GetProjectAnalysis(arg1) {
  return window['go']['main']['App']['GetProjectAnalysis'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetTokenUsage(arg1) {
  return window['go']['main']['App']['GetTokenUsage'](arg1);
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function GitBranch(arg1) {
  return window['go']['main']['App']['GitBranch'](arg1);
}

export function GitCheckout(arg1, arg2) {
  return window['go']['main']['App']['GitCheckout'](arg1, arg2);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitCreateBranch(arg1, arg2) {
  return window['go']['main']['App']['GitCreateBranch'](arg1, arg2);
}

export function GitDiff(arg1, arg2) {
  return window['go']['main']['App']['GitDiff'](arg1, arg2);
}

export function GitFetch(arg1) {
  return window['go']['main']['App']['GitFetch'](arg1);
}

export function GitLog(arg1, arg2) {
  return window['go']['main']['App']['GitLog'](arg1, arg2);
}

export function GitMerge(arg1, arg2) {
  return window['go']['main']['App']['GitMerge'](arg1, arg2);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitPush(arg1) {
  return window['go']['main']['App']['GitPush'](arg1);
}

export function GitStage(arg1, arg2) {
  return window['go']['main']['App']['GitStage'](arg1, arg2);
}

export function GitStash(arg1, arg2) {
  return window['go']['main']['App']['GitStash'](arg1, arg2);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function GitStatusAndBranch(arg1) {
  return window['go']['main']['App']['GitStatusAndBranch'](arg1);
}

export function GitUnstage(arg1, arg2) {
  return window['go']['main']['App']['GitUnstage'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallSkillFromURL(arg1) {
  return window['go']['main']['App']['InstallSkillFromURL'](arg1);
}

export function IsProviderConfigured() {
  return window['go']['main']['App']['IsProviderConfigured']();
}

export function KillTerminal(arg1) {
  return window['go']['main']['App']['KillTerminal'](arg1);
}

export function LSPCloseFile(arg1) {
  return window['go']['main']['App']['LSPCloseFile'](arg1);
}

export function LSPCompletions(arg1, arg2, arg3) {
  return window['go']['main']['App']['LSPCompletions'](arg1, arg2, arg3);
}

export function LSPDefinition(arg1, arg2, arg3) {
  return window['go']['main']['App']['LSPDefinition'](arg1, arg2, arg3);
}

export function LSPDidChange(arg1, arg2) {
  return window['go']['main']['App']['LSPDidChange'](arg1, arg2);
}

export function LSPDidOpen(arg1, arg2) {
  return window['go']['main']['App']['LSPDidOpen'](arg1, arg2);
}

export function LSPHover(arg1, arg2, arg3) {
  return window['go']['main']['App']['LSPHover'](arg1, arg2, arg3);
}

export function LSPShutdown() {
  return window['go']['main']['App']['LSPShutdown']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListTerminals() {
  return window['go']['main']['App']['ListTerminals']();
}

export function LoadCustomModels() {
  return window['go']['main']['App']['LoadCustomModels']();
}

export function LoadEditorSettings() {
  return window['go']['main']['App']['LoadEditorSettings']();
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function NewTerminal(arg1) {
  return window['go']['main']['App']['NewTerminal'](arg1);
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileWithLSP(arg1) {
  return window['go']['main']['App']['ReadFileWithLSP'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function ReplaceInFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReplaceInFiles'](arg1, arg2, arg3);
}

export function SaveConversation(arg1) {
  return window['go']['main']['App']['SaveConversation'](arg1);
}

export function SaveCustomModels(arg1) {
  return window['go']['main']['App']['SaveCustomModels'](arg1);
}

export function SaveEditorSettings(arg1) {
  return window['go']['main']['App']['SaveEditorSettings'](arg1);
}

export function SaveKnowledge(arg1) {
  return window['go']['main']['App']['SaveKnowledge'](arg1);
}

export function SaveMessage(arg1) {
  return window['go']['main']['App']['SaveMessage'](arg1);
}

export function SaveSkill(arg1) {
  return window['go']['main']['App']['SaveSkill'](arg1);
}

export function SaveTokenUsageEntry(arg1) {
  return window['go']['main']['App']['SaveTokenUsageEntry'](arg1);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2);
}

export function SetProjectPath(arg1) {
  return window['go']['main']['App']['SetProjectPath'](arg1);
}

export function SetProviderConfig(arg1, arg2) {
  return window['go']['main']['App']['SetProviderConfig'](arg1, arg2);
}

export function SetToolAutoApprove(arg1, arg2) {
  return window['go']['main']['App']['SetToolAutoApprove'](arg1, arg2);
}

export function StartMCPServer(arg1) {
  return window['go']['main']['App']['StartMCPServer'](arg1);
}

export function StartTerminal(arg1) {
  return window['go']['main']['App']['StartTerminal'](arg1);
}

export function StopGenerating() {
  return window['go']['main']['App']['StopGenerating']();
}

export function StopMCPServer(arg1) {
  return window['go']['main']['App']['StopMCPServer'](arg1);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['main']['App']['TerminalWrite'](arg1, arg2);
}

export function TestProvider(arg1) {
  return window['go']['main']['App']['TestProvider'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteFileWithLSP(arg1, arg2) {
  return window['go']['main']['App']['WriteFileWithLSP'](arg1, arg2);
}
