// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIChat(arg1) {
  return window['go']['main']['App']['AIChat'](arg1);
}

export function AIChatStream(arg1) {
  return window['go']['main']['App']['AIChatStream'](arg1);
}

export function AICompletion(arg1, arg2) {
  return window['go']['main']['App']['AICompletion'](arg1, arg2);
}

export function AddLSPServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddLSPServer'](arg1, arg2, arg3, arg4);
}

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function AddRemoteConnection(arg1) {
  return window['go']['main']['App']['AddRemoteConnection'](arg1);
}

export function AddWorkspaceRoot(arg1) {
  return window['go']['main']['App']['AddWorkspaceRoot'](arg1);
}

export function AnalyzeProject(arg1) {
  return window['go']['main']['App']['AnalyzeProject'](arg1);
}

export function ApplyDiff(arg1) {
  return window['go']['main']['App']['ApplyDiff'](arg1);
}

export function CheckCommandExists(arg1) {
  return window['go']['main']['App']['CheckCommandExists'](arg1);
}

export function ClearTokenUsage() {
  return window['go']['main']['App']['ClearTokenUsage']();
}

export function CloseProject(arg1) {
  return window['go']['main']['App']['CloseProject'](arg1);
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function CodeComplete(arg1) {
  return window['go']['main']['App']['CodeComplete'](arg1);
}

export function CodeCompleteMultiLine(arg1) {
  return window['go']['main']['App']['CodeCompleteMultiLine'](arg1);
}

export function CodeScanFile(arg1, arg2) {
  return window['go']['main']['App']['CodeScanFile'](arg1, arg2);
}

export function CodeScanRules() {
  return window['go']['main']['App']['CodeScanRules']();
}

export function CodeScanStats() {
  return window['go']['main']['App']['CodeScanStats']();
}

export function ComputeDiff(arg1, arg2) {
  return window['go']['main']['App']['ComputeDiff'](arg1, arg2);
}

export function ConnectRemote(arg1) {
  return window['go']['main']['App']['ConnectRemote'](arg1);
}

export function ConnectTerminal(arg1) {
  return window['go']['main']['App']['ConnectTerminal'](arg1);
}

export function ContinueAgentLoop(arg1) {
  return window['go']['main']['App']['ContinueAgentLoop'](arg1);
}

export function CreateDir(arg1) {
  return window['go']['main']['App']['CreateDir'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function DebugAddBreakpoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DebugAddBreakpoint'](arg1, arg2, arg3, arg4);
}

export function DebugAddBreakpointByFunc(arg1, arg2) {
  return window['go']['main']['App']['DebugAddBreakpointByFunc'](arg1, arg2);
}

export function DebugCheckDlv() {
  return window['go']['main']['App']['DebugCheckDlv']();
}

export function DebugConsoleExecute(arg1, arg2) {
  return window['go']['main']['App']['DebugConsoleExecute'](arg1, arg2);
}

export function DebugContinue(arg1) {
  return window['go']['main']['App']['DebugContinue'](arg1);
}

export function DebugDetach(arg1) {
  return window['go']['main']['App']['DebugDetach'](arg1);
}

export function DebugGetState(arg1) {
  return window['go']['main']['App']['DebugGetState'](arg1);
}

export function DebugGetVariable(arg1, arg2, arg3) {
  return window['go']['main']['App']['DebugGetVariable'](arg1, arg2, arg3);
}

export function DebugList() {
  return window['go']['main']['App']['DebugList']();
}

export function DebugListBreakpoints(arg1) {
  return window['go']['main']['App']['DebugListBreakpoints'](arg1);
}

export function DebugRemoveBreakpoint(arg1, arg2) {
  return window['go']['main']['App']['DebugRemoveBreakpoint'](arg1, arg2);
}

export function DebugRestart(arg1) {
  return window['go']['main']['App']['DebugRestart'](arg1);
}

export function DebugStart(arg1, arg2) {
  return window['go']['main']['App']['DebugStart'](arg1, arg2);
}

export function DebugStepIn(arg1) {
  return window['go']['main']['App']['DebugStepIn'](arg1);
}

export function DebugStepOut(arg1) {
  return window['go']['main']['App']['DebugStepOut'](arg1);
}

export function DebugStepOver(arg1) {
  return window['go']['main']['App']['DebugStepOver'](arg1);
}

export function DebugStop(arg1) {
  return window['go']['main']['App']['DebugStop'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteConversationMessages(arg1) {
  return window['go']['main']['App']['DeleteConversationMessages'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteKnowledge(arg1) {
  return window['go']['main']['App']['DeleteKnowledge'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DisconnectRemote(arg1) {
  return window['go']['main']['App']['DisconnectRemote'](arg1);
}

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function ExecuteSkill(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteSkill'](arg1, arg2, arg3, arg4);
}

export function ExecuteToolCall(arg1) {
  return window['go']['main']['App']['ExecuteToolCall'](arg1);
}

export function FormatFile(arg1) {
  return window['go']['main']['App']['FormatFile'](arg1);
}

export function GetAgentConfig(arg1) {
  return window['go']['main']['App']['GetAgentConfig'](arg1);
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetConversations(arg1) {
  return window['go']['main']['App']['GetConversations'](arg1);
}

export function GetExtensionCommands() {
  return window['go']['main']['App']['GetExtensionCommands']();
}

export function GetExtensions() {
  return window['go']['main']['App']['GetExtensions']();
}

export function GetKnowledge(arg1) {
  return window['go']['main']['App']['GetKnowledge'](arg1);
}

export function GetLSPServers() {
  return window['go']['main']['App']['GetLSPServers']();
}

export function GetLanguagePackages() {
  return window['go']['main']['App']['GetLanguagePackages']();
}

export function GetMCPServers() {
  return window['go']['main']['App']['GetMCPServers']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetModels(arg1) {
  return window['go']['main']['App']['GetModels'](arg1);
}

export function GetOpenProjects() {
  return window['go']['main']['App']['GetOpenProjects']();
}

export function GetProjectAnalysis(arg1) {
  return window['go']['main']['App']['GetProjectAnalysis'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetProxy() {
  return window['go']['main']['App']['GetProxy']();
}

export function GetRecentConversations(arg1, arg2) {
  return window['go']['main']['App']['GetRecentConversations'](arg1, arg2);
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetTokenUsage(arg1) {
  return window['go']['main']['App']['GetTokenUsage'](arg1);
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function GetWorkspaceRoots() {
  return window['go']['main']['App']['GetWorkspaceRoots']();
}

export function GitBlame(arg1, arg2) {
  return window['go']['main']['App']['GitBlame'](arg1, arg2);
}

export function GitBranch(arg1) {
  return window['go']['main']['App']['GitBranch'](arg1);
}

export function GitCheckout(arg1, arg2) {
  return window['go']['main']['App']['GitCheckout'](arg1, arg2);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitConflictFiles(arg1) {
  return window['go']['main']['App']['GitConflictFiles'](arg1);
}

export function GitCreateBranch(arg1, arg2) {
  return window['go']['main']['App']['GitCreateBranch'](arg1, arg2);
}

export function GitDiff(arg1, arg2) {
  return window['go']['main']['App']['GitDiff'](arg1, arg2);
}

export function GitDiffBetween(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitDiffBetween'](arg1, arg2, arg3, arg4);
}

export function GitFetch(arg1) {
  return window['go']['main']['App']['GitFetch'](arg1);
}

export function GitLog(arg1, arg2) {
  return window['go']['main']['App']['GitLog'](arg1, arg2);
}

export function GitLogFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitLogFile'](arg1, arg2, arg3);
}

export function GitMerge(arg1, arg2) {
  return window['go']['main']['App']['GitMerge'](arg1, arg2);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitPush(arg1) {
  return window['go']['main']['App']['GitPush'](arg1);
}

export function GitRemoteList(arg1) {
  return window['go']['main']['App']['GitRemoteList'](arg1);
}

export function GitStage(arg1, arg2) {
  return window['go']['main']['App']['GitStage'](arg1, arg2);
}

export function GitStash(arg1, arg2) {
  return window['go']['main']['App']['GitStash'](arg1, arg2);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function GitStatusAndBranch(arg1) {
  return window['go']['main']['App']['GitStatusAndBranch'](arg1);
}

export function GitUnstage(arg1, arg2) {
  return window['go']['main']['App']['GitUnstage'](arg1, arg2);
}

export function GitVisualDiff(arg1, arg2) {
  return window['go']['main']['App']['GitVisualDiff'](arg1, arg2);
}

export function IndexProject(arg1) {
  return window['go']['main']['App']['IndexProject'](arg1);
}

export function InstallLanguagePackage(arg1) {
  return window['go']['main']['App']['InstallLanguagePackage'](arg1);
}

export function InstallSkillFromURL(arg1) {
  return window['go']['main']['App']['InstallSkillFromURL'](arg1);
}

export function IsProviderConfigured() {
  return window['go']['main']['App']['IsProviderConfigured']();
}

export function KillTerminal(arg1) {
  return window['go']['main']['App']['KillTerminal'](arg1);
}

export function LSPCloseFile(arg1) {
  return window['go']['main']['App']['LSPCloseFile'](arg1);
}

export function LSPCodeActions(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LSPCodeActions'](arg1, arg2, arg3, arg4, arg5);
}

export function LSPCodeLens(arg1) {
  return window['go']['main']['App']['LSPCodeLens'](arg1);
}

export function LSPCompletions(arg1, arg2, arg3) {
  return window['go']['main']['App']['LSPCompletions'](arg1, arg2, arg3);
}

export function LSPDefinition(arg1, arg2, arg3) {
  return window['go']['main']['App']['LSPDefinition'](arg1, arg2, arg3);
}

export function LSPDidChange(arg1, arg2) {
  return window['go']['main']['App']['LSPDidChange'](arg1, arg2);
}

export function LSPDidOpen(arg1, arg2) {
  return window['go']['main']['App']['LSPDidOpen'](arg1, arg2);
}

export function LSPDocumentSymbols(arg1) {
  return window['go']['main']['App']['LSPDocumentSymbols'](arg1);
}

export function LSPFoldingRanges(arg1) {
  return window['go']['main']['App']['LSPFoldingRanges'](arg1);
}

export function LSPFormatting(arg1) {
  return window['go']['main']['App']['LSPFormatting'](arg1);
}

export function LSPHover(arg1, arg2, arg3) {
  return window['go']['main']['App']['LSPHover'](arg1, arg2, arg3);
}

export function LSPInlayHints(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LSPInlayHints'](arg1, arg2, arg3, arg4, arg5);
}

export function LSPReferences(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSPReferences'](arg1, arg2, arg3, arg4);
}

export function LSPRename(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSPRename'](arg1, arg2, arg3, arg4);
}

export function LSPShutdown() {
  return window['go']['main']['App']['LSPShutdown']();
}

export function LSPSignatureHelp(arg1, arg2, arg3) {
  return window['go']['main']['App']['LSPSignatureHelp'](arg1, arg2, arg3);
}

export function LSPWorkspaceSymbols(arg1) {
  return window['go']['main']['App']['LSPWorkspaceSymbols'](arg1);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListPipelines() {
  return window['go']['main']['App']['ListPipelines']();
}

export function ListRemoteConnections() {
  return window['go']['main']['App']['ListRemoteConnections']();
}

export function ListTerminals() {
  return window['go']['main']['App']['ListTerminals']();
}

export function ListTerminalsByProject(arg1) {
  return window['go']['main']['App']['ListTerminalsByProject'](arg1);
}

export function LoadCustomModels() {
  return window['go']['main']['App']['LoadCustomModels']();
}

export function LoadEditorSettings() {
  return window['go']['main']['App']['LoadEditorSettings']();
}

export function LoadSessionState() {
  return window['go']['main']['App']['LoadSessionState']();
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function NewTerminal(arg1) {
  return window['go']['main']['App']['NewTerminal'](arg1);
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function QuickVerifyFile(arg1) {
  return window['go']['main']['App']['QuickVerifyFile'](arg1);
}

export function RAGIndexFileIncremental(arg1, arg2) {
  return window['go']['main']['App']['RAGIndexFileIncremental'](arg1, arg2);
}

export function RAGIndexStats(arg1) {
  return window['go']['main']['App']['RAGIndexStats'](arg1);
}

export function RAGRemoveFileFromIndex(arg1, arg2) {
  return window['go']['main']['App']['RAGRemoveFileFromIndex'](arg1, arg2);
}

export function RAGSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['RAGSearch'](arg1, arg2, arg3);
}

export function RAGSearchHybrid(arg1, arg2, arg3) {
  return window['go']['main']['App']['RAGSearchHybrid'](arg1, arg2, arg3);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileWithLSP(arg1) {
  return window['go']['main']['App']['ReadFileWithLSP'](arg1);
}

export function RemoveLSPServer(arg1) {
  return window['go']['main']['App']['RemoveLSPServer'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RemoveRemoteConnection(arg1) {
  return window['go']['main']['App']['RemoveRemoteConnection'](arg1);
}

export function RemoveWorkspaceRoot(arg1) {
  return window['go']['main']['App']['RemoveWorkspaceRoot'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function ReplaceInFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReplaceInFiles'](arg1, arg2, arg3);
}

export function RespondToAsk(arg1) {
  return window['go']['main']['App']['RespondToAsk'](arg1);
}

export function RespondToolApproval(arg1, arg2) {
  return window['go']['main']['App']['RespondToolApproval'](arg1, arg2);
}

export function RunPipeline(arg1) {
  return window['go']['main']['App']['RunPipeline'](arg1);
}

export function RunTests(arg1) {
  return window['go']['main']['App']['RunTests'](arg1);
}

export function SaveConversation(arg1) {
  return window['go']['main']['App']['SaveConversation'](arg1);
}

export function SaveCustomModels(arg1) {
  return window['go']['main']['App']['SaveCustomModels'](arg1);
}

export function SaveEditorSettings(arg1) {
  return window['go']['main']['App']['SaveEditorSettings'](arg1);
}

export function SaveKnowledge(arg1) {
  return window['go']['main']['App']['SaveKnowledge'](arg1);
}

export function SaveMessage(arg1) {
  return window['go']['main']['App']['SaveMessage'](arg1);
}

export function SaveSessionState(arg1) {
  return window['go']['main']['App']['SaveSessionState'](arg1);
}

export function SaveSkill(arg1) {
  return window['go']['main']['App']['SaveSkill'](arg1);
}

export function SaveTokenUsageEntry(arg1) {
  return window['go']['main']['App']['SaveTokenUsageEntry'](arg1);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2);
}

export function SetActiveWorkspaceRoot(arg1) {
  return window['go']['main']['App']['SetActiveWorkspaceRoot'](arg1);
}

export function SetExtensionEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetExtensionEnabled'](arg1, arg2);
}

export function SetProjectPath(arg1) {
  return window['go']['main']['App']['SetProjectPath'](arg1);
}

export function SetProviderConfig(arg1, arg2) {
  return window['go']['main']['App']['SetProviderConfig'](arg1, arg2);
}

export function SetProxy(arg1, arg2) {
  return window['go']['main']['App']['SetProxy'](arg1, arg2);
}

export function SetToolAutoApprove(arg1, arg2) {
  return window['go']['main']['App']['SetToolAutoApprove'](arg1, arg2);
}

export function StartMCPServer(arg1) {
  return window['go']['main']['App']['StartMCPServer'](arg1);
}

export function StartTerminal(arg1) {
  return window['go']['main']['App']['StartTerminal'](arg1);
}

export function StopGenerating() {
  return window['go']['main']['App']['StopGenerating']();
}

export function StopMCPServer(arg1) {
  return window['go']['main']['App']['StopMCPServer'](arg1);
}

export function StopPipeline() {
  return window['go']['main']['App']['StopPipeline']();
}

export function SwitchProject(arg1) {
  return window['go']['main']['App']['SwitchProject'](arg1);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['main']['App']['TerminalWrite'](arg1, arg2);
}

export function TestProvider(arg1) {
  return window['go']['main']['App']['TestProvider'](arg1);
}

export function VerifyFile(arg1) {
  return window['go']['main']['App']['VerifyFile'](arg1);
}

export function VerifyProject() {
  return window['go']['main']['App']['VerifyProject']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteFileWithLSP(arg1, arg2) {
  return window['go']['main']['App']['WriteFileWithLSP'](arg1, arg2);
}
