// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {provider} from '../models';
import {mcp} from '../models';
import {remote} from '../models';
import {main} from '../models';
import {completion} from '../models';
import {codescan} from '../models';
import {files} from '../models';
import {debug} from '../models';
import {skill} from '../models';
import {agent} from '../models';
import {memory} from '../models';
import {extension} from '../models';
import {lsp} from '../models';
import {workspace} from '../models';
import {git} from '../models';
import {verify} from '../models';
import {rag} from '../models';
import {tools} from '../models';
import {pipeline} from '../models';

export function AIChat(arg1:provider.ChatRequest):Promise<string>;

export function AIChatStream(arg1:provider.ChatRequest):Promise<void>;

export function AICompletion(arg1:string,arg2:provider.CompletionRequest):Promise<string>;

export function AddLSPServer(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>):Promise<void>;

export function AddMCPServer(arg1:mcp.MCPServerConfig):Promise<void>;

export function AddRemoteConnection(arg1:remote.Connection):Promise<void>;

export function AddWorkspaceRoot(arg1:string):Promise<void>;

export function AnalyzeProject(arg1:string):Promise<string>;

export function ApplyDiff(arg1:main.ApplyDiffRequest):Promise<void>;

export function CheckCommandExists(arg1:string):Promise<boolean>;

export function ClearTokenUsage():Promise<void>;

export function CloseProject(arg1:string):Promise<void>;

export function CloseWindow():Promise<void>;

export function CodeComplete(arg1:main.CodeCompleteRequest):Promise<completion.Suggestion>;

export function CodeCompleteMultiLine(arg1:main.CodeCompleteRequest):Promise<completion.Suggestion>;

export function CodeScanFile(arg1:string,arg2:string):Promise<codescan.ScanResult>;

export function CodeScanRules():Promise<Array<codescan.Rule>>;

export function CodeScanStats():Promise<Record<string, number>>;

export function ComputeDiff(arg1:string,arg2:string):Promise<Array<files.DiffHunk>>;

export function ConnectRemote(arg1:string):Promise<void>;

export function ConnectTerminal(arg1:string):Promise<void>;

export function ContinueAgentLoop(arg1:number):Promise<void>;

export function CreateDir(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function DebugAddBreakpoint(arg1:string,arg2:string,arg3:number,arg4:string):Promise<debug.Breakpoint>;

export function DebugAddBreakpointByFunc(arg1:string,arg2:string):Promise<debug.Breakpoint>;

export function DebugCheckDlv():Promise<boolean|string>;

export function DebugConsoleExecute(arg1:string,arg2:string):Promise<debug.ConsoleResult>;

export function DebugContinue(arg1:string):Promise<void>;

export function DebugDetach(arg1:string):Promise<void>;

export function DebugGetState(arg1:string):Promise<debug.SessionState>;

export function DebugGetVariable(arg1:string,arg2:number,arg3:string):Promise<debug.Variable>;

export function DebugList():Promise<Array<Record<string, any>>>;

export function DebugListBreakpoints(arg1:string):Promise<Array<debug.Breakpoint>>;

export function DebugRemoveBreakpoint(arg1:string,arg2:number):Promise<void>;

export function DebugRestart(arg1:string):Promise<void>;

export function DebugStart(arg1:string,arg2:Array<string>):Promise<Record<string, any>>;

export function DebugStepIn(arg1:string):Promise<void>;

export function DebugStepOut(arg1:string):Promise<void>;

export function DebugStepOver(arg1:string):Promise<void>;

export function DebugStop(arg1:string):Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteConversationMessages(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteKnowledge(arg1:string):Promise<void>;

export function DeleteMessage(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DisconnectRemote(arg1:string):Promise<void>;

export function ExecuteCommand(arg1:string):Promise<string>;

export function ExecuteSkill(arg1:string,arg2:skill.SkillContext,arg3:string,arg4:string):Promise<void>;

export function ExecuteToolCall(arg1:agent.ToolCall):Promise<agent.ToolResult>;

export function FormatFile(arg1:string):Promise<string>;

export function GetAgentConfig(arg1:string):Promise<agent.AgentDef>;

export function GetAgents():Promise<Array<agent.AgentDef>>;

export function GetConversations(arg1:string):Promise<Array<memory.Conversation>>;

export function GetExtensionCommands():Promise<Array<extension.CommandContribution>>;

export function GetExtensions():Promise<Array<extension.Extension>>;

export function GetKnowledge(arg1:string):Promise<Array<memory.Knowledge>>;

export function GetLSPServers():Promise<Array<lsp.FrontendServerInfo>>;

export function GetLanguagePackages():Promise<Array<lsp.LanguagePackage>>;

export function GetMCPServers():Promise<Array<mcp.MCPServerConfig>>;

export function GetMessages(arg1:string):Promise<Array<memory.Message>>;

export function GetModels(arg1:string):Promise<Array<provider.Model>>;

export function GetOpenProjects():Promise<Array<string>>;

export function GetProjectAnalysis(arg1:string):Promise<string>;

export function GetProviders():Promise<Array<provider.ProviderInfo>>;

export function GetProxy():Promise<string|string>;

export function GetRecentConversations(arg1:string,arg2:number):Promise<Array<memory.Conversation>>;

export function GetSkills():Promise<Array<skill.SkillDef>>;

export function GetTokenUsage(arg1:string):Promise<memory.TokenUsageStats>;

export function GetTools():Promise<Array<agent.ToolDef>>;

export function GetWorkspaceRoots():Promise<Array<workspace.WorkspaceRoot>>;

export function GitBlame(arg1:string,arg2:string):Promise<Array<git.BlameLine>>;

export function GitBranch(arg1:string):Promise<string>;

export function GitCheckout(arg1:string,arg2:string):Promise<string>;

export function GitCommit(arg1:string,arg2:string):Promise<void>;

export function GitConflictFiles(arg1:string):Promise<Array<string>>;

export function GitCreateBranch(arg1:string,arg2:string):Promise<string>;

export function GitDiff(arg1:string,arg2:string):Promise<string>;

export function GitDiffBetween(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GitFetch(arg1:string):Promise<string>;

export function GitLog(arg1:string,arg2:number):Promise<Array<git.LogEntry>>;

export function GitLogFile(arg1:string,arg2:string,arg3:number):Promise<Array<git.LogEntry>>;

export function GitMerge(arg1:string,arg2:string):Promise<string>;

export function GitPull(arg1:string):Promise<string>;

export function GitPush(arg1:string):Promise<string>;

export function GitRemoteList(arg1:string):Promise<string>;

export function GitStage(arg1:string,arg2:string):Promise<void>;

export function GitStash(arg1:string,arg2:string):Promise<string>;

export function GitStatus(arg1:string):Promise<Array<git.StatusEntry>>;

export function GitStatusAndBranch(arg1:string):Promise<Record<string, any>>;

export function GitUnstage(arg1:string,arg2:string):Promise<void>;

export function GitVisualDiff(arg1:string,arg2:string):Promise<string>;

export function IndexProject(arg1:string):Promise<void>;

export function InstallLanguagePackage(arg1:string):Promise<string>;

export function InstallSkillFromURL(arg1:string):Promise<void>;

export function IsProviderConfigured():Promise<boolean>;

export function KillTerminal(arg1:string):Promise<void>;

export function LSPCloseFile(arg1:string):Promise<void>;

export function LSPCodeActions(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Array<lsp.FrontendCodeAction>>;

export function LSPCodeLens(arg1:string):Promise<Array<lsp.CodeLens>>;

export function LSPCompletions(arg1:string,arg2:number,arg3:number):Promise<Array<lsp.FrontendCompletion>>;

export function LSPDefinition(arg1:string,arg2:number,arg3:number):Promise<Array<lsp.Location>>;

export function LSPDidChange(arg1:string,arg2:string):Promise<void>;

export function LSPDidOpen(arg1:string,arg2:string):Promise<void>;

export function LSPDocumentSymbols(arg1:string):Promise<Array<lsp.DocumentSymbol>>;

export function LSPFoldingRanges(arg1:string):Promise<Array<lsp.FoldingRange>>;

export function LSPFormatting(arg1:string):Promise<Array<lsp.TextEdit>>;

export function LSPHover(arg1:string,arg2:number,arg3:number):Promise<lsp.Hover>;

export function LSPInlayHints(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Array<lsp.InlayHint>>;

export function LSPReferences(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<Array<lsp.FrontendLocation>>;

export function LSPRename(arg1:string,arg2:number,arg3:number,arg4:string):Promise<lsp.RenameResult>;

export function LSPShutdown():Promise<void>;

export function LSPSignatureHelp(arg1:string,arg2:number,arg3:number):Promise<lsp.SignatureHelp>;

export function LSPWorkspaceSymbols(arg1:string):Promise<Array<lsp.WorkspaceSymbol>>;

export function ListDir(arg1:string):Promise<Array<files.FileInfo>>;

export function ListPipelines():Promise<Array<main.PipelineInfo>>;

export function ListRemoteConnections():Promise<Array<remote.Connection>>;

export function ListTerminals():Promise<Array<Record<string, any>>>;

export function ListTerminalsByProject(arg1:string):Promise<Array<Record<string, any>>>;

export function LoadCustomModels():Promise<Array<main.CustomModelEntry>>;

export function LoadEditorSettings():Promise<string>;

export function LoadSessionState():Promise<memory.SessionState>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function NewTerminal(arg1:string):Promise<string>;

export function OpenFolder():Promise<string>;

export function QuickVerifyFile(arg1:string):Promise<verify.CheckResult>;

export function RAGIndexFileIncremental(arg1:string,arg2:string):Promise<void>;

export function RAGIndexStats(arg1:string):Promise<Record<string, any>>;

export function RAGRemoveFileFromIndex(arg1:string,arg2:string):Promise<void>;

export function RAGSearch(arg1:string,arg2:string,arg3:number):Promise<Array<rag.SearchResult>>;

export function RAGSearchHybrid(arg1:string,arg2:string,arg3:number):Promise<Array<rag.SearchResult>>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileWithLSP(arg1:string):Promise<string>;

export function RemoveLSPServer(arg1:string):Promise<void>;

export function RemoveMCPServer(arg1:string):Promise<void>;

export function RemoveRemoteConnection(arg1:string):Promise<void>;

export function RemoveWorkspaceRoot(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function ReplaceInFiles(arg1:string,arg2:string,arg3:files.SearchOptions):Promise<void>;

export function RespondToAsk(arg1:tools.AskUserResponse):Promise<boolean>;

export function RespondToolApproval(arg1:string,arg2:boolean):Promise<boolean>;

export function RunPipeline(arg1:main.RunPipelineRequest):Promise<pipeline.PipelineRun>;

export function RunTests(arg1:string):Promise<Array<verify.TestSuiteResult>>;

export function SaveConversation(arg1:memory.Conversation):Promise<void>;

export function SaveCustomModels(arg1:Array<main.CustomModelEntry>):Promise<void>;

export function SaveEditorSettings(arg1:string):Promise<void>;

export function SaveKnowledge(arg1:memory.Knowledge):Promise<void>;

export function SaveMessage(arg1:memory.Message):Promise<void>;

export function SaveSessionState(arg1:memory.SessionState):Promise<void>;

export function SaveSkill(arg1:skill.SkillDef):Promise<void>;

export function SaveTokenUsageEntry(arg1:memory.TokenUsageEntry):Promise<void>;

export function SearchFiles(arg1:string,arg2:files.SearchOptions):Promise<Array<files.SearchResult>>;

export function SetActiveWorkspaceRoot(arg1:string):Promise<void>;

export function SetExtensionEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetProjectPath(arg1:string):Promise<void>;

export function SetProviderConfig(arg1:string,arg2:provider.ProviderConfig):Promise<void>;

export function SetProxy(arg1:string,arg2:string):Promise<void>;

export function SetToolAutoApprove(arg1:string,arg2:boolean):Promise<void>;

export function StartMCPServer(arg1:string):Promise<void>;

export function StartTerminal(arg1:string):Promise<void>;

export function StopGenerating():Promise<void>;

export function StopMCPServer(arg1:string):Promise<void>;

export function StopPipeline():Promise<void>;

export function SwitchProject(arg1:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TerminalWrite(arg1:string,arg2:string):Promise<void>;

export function TestProvider(arg1:string):Promise<void>;

export function VerifyFile(arg1:string):Promise<verify.VerificationResult>;

export function VerifyProject():Promise<verify.VerificationResult>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteFileWithLSP(arg1:string,arg2:string):Promise<void>;
